#pragma once
#include <vector>
#include <string>
#include <map>

std::vector<std::string> pokemonNamesVec
{
    "Bulbasaur",
    "Ivysaur",
    "Venusaur",
    "Charmander",
    "Charmeleon",
    "Charizard",
    "Squirtle",
    "Wartortle",
    "Blastoise",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Pidgey",
    "Pidgeotto",
    "Pidgeot",
    "Rattata",
    "Raticate",
    "Spearow",
    "Fearow",
    "Ekans",
    "Arbok",
    "Pikachu",
    "Raichu",
    "Sandshrew",
    "Sandslash",
    "Nidoran♀",
    "Nidorina",
    "Nidoqueen",
    "Nidoran♂",
    "Nidorino",
    "Nidoking",
    "Clefairy",
    "Clefable",
    "Vulpix",
    "Ninetales",
    "Jigglypuff",
    "Wigglytuff",
    "Zubat",
    "Golbat",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Paras",
    "Parasect",
    "Venonat",
    "Venomoth",
    "Diglett",
    "Dugtrio",
    "Meowth",
    "Persian",
    "Psyduck",
    "Golduck",
    "Mankey",
    "Primeape",
    "Growlithe",
    "Arcanine",
    "Poliwag",
    "Poliwhirl",
    "Poliwrath",
    "Abra",
    "Kadabra",
    "Alakazam",
    "Machop",
    "Machoke",
    "Machamp",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Tentacool",
    "Tentacruel",
    "Geodude",
    "Graveler",
    "Golem",
    "Ponyta",
    "Rapidash",
    "Slowpoke",
    "Slowbro",
    "Magnemite",
    "Magneton",
    "Farfetch’d",
    "Doduo",
    "Dodrio",
    "Seel",
    "Dewgong",
    "Grimer",
    "Muk",
    "Shellder",
    "Cloyster",
    "Gastly",
    "Haunter",
    "Gengar",
    "Onix",
    "Drowzee",
    "Hypno",
    "Krabby",
    "Kingler",
    "Voltorb",
    "Electrode",
    "Exeggcute",
    "Exeggutor",
    "Cubone",
    "Marowak",
    "Hitmonlee",
    "Hitmonchan",
    "Lickitung",
    "Koffing",
    "Weezing",
    "Rhyhorn",
    "Rhydon",
    "Chansey",
    "Tangela",
    "Kangaskhan",
    "Horsea",
    "Seadra",
    "Goldeen",
    "Seaking",
    "Staryu",
    "Starmie",
    "Mr. Mime",
    "Scyther",
    "Jynx",
    "Electabuzz",
    "Magmar",
    "Pinsir",
    "Tauros",
    "Magikarp",
    "Gyarados",
    "Lapras",
    "Ditto",
    "Eevee",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Porygon",
    "Omanyte",
    "Omastar",
    "Kabuto",
    "Kabutops",
    "Aerodactyl",
    "Snorlax",
    "Articuno",
    "Zapdos",
    "Moltres",
    "Dratini",
    "Dragonair",
    "Dragonite",
    "Mewtwo",
    "Mew",
    "Chikorita",
    "Bayleef",
    "Meganium",
    "Cyndaquil",
    "Quilava",
    "Typhlosion",
    "Totodile",
    "Croconaw",
    "Feraligatr",
    "Sentret",
    "Furret",
    "Hoothoot",
    "Noctowl",
    "Ledyba",
    "Ledian",
    "Spinarak",
    "Ariados",
    "Crobat",
    "Chinchou",
    "Lanturn",
    "Pichu",
    "Cleffa",
    "Igglybuff",
    "Togepi",
    "Togetic",
    "Natu",
    "Xatu",
    "Mareep",
    "Flaaffy",
    "Ampharos",
    "Bellossom",
    "Marill",
    "Azumarill",
    "Sudowoodo",
    "Politoed",
    "Hoppip",
    "Skiploom",
    "Jumpluff",
    "Aipom",
    "Sunkern",
    "Sunflora",
    "Yanma",
    "Wooper",
    "Quagsire",
    "Espeon",
    "Umbreon",
    "Murkrow",
    "Slowking",
    "Misdreavus",
    "Unown",
    "Wobbuffet",
    "Girafarig",
    "Pineco",
    "Forretress",
    "Dunsparce",
    "Gligar",
    "Steelix",
    "Snubbull",
    "Granbull",
    "Qwilfish",
    "Scizor",
    "Shuckle",
    "Heracross",
    "Sneasel",
    "Teddiursa",
    "Ursaring",
    "Slugma",
    "Magcargo",
    "Swinub",
    "Piloswine",
    "Corsola",
    "Remoraid",
    "Octillery",
    "Delibird",
    "Mantine",
    "Skarmory",
    "Houndour",
    "Houndoom",
    "Kingdra",
    "Phanpy",
    "Donphan",
    "Porygon2",
    "Stantler",
    "Smeargle",
    "Tyrogue",
    "Hitmontop",
    "Smoochum",
    "Elekid",
    "Magby",
    "Miltank",
    "Blissey",
    "Raikou",
    "Entei",
    "Suicune",
    "Larvitar",
    "Pupitar",
    "Tyranitar",
    "Lugia",
    "Ho-Oh",
    "Celebi",
    "Treecko",
    "Grovyle",
    "Sceptile",
    "Torchic",
    "Combusken",
    "Blaziken",
    "Mudkip",
    "Marshtomp",
    "Swampert",
    "Poochyena",
    "Mightyena",
    "Zigzagoon",
    "Linoone",
    "Wurmple",
    "Silcoon",
    "Beautifly",
    "Cascoon",
    "Dustox",
    "Lotad",
    "Lombre",
    "Ludicolo",
    "Seedot",
    "Nuzleaf",
    "Shiftry",
    "Taillow",
    "Swellow",
    "Wingull",
    "Pelipper",
    "Ralts",
    "Kirlia",
    "Gardevoir",
    "Surskit",
    "Masquerain",
    "Shroomish",
    "Breloom",
    "Slakoth",
    "Vigoroth",
    "Slaking",
    "Nincada",
    "Ninjask",
    "Shedinja",
    "Whismur",
    "Loudred",
    "Exploud",
    "Makuhita",
    "Hariyama",
    "Azurill",
    "Nosepass",
    "Skitty",
    "Delcatty",
    "Sableye",
    "Mawile",
    "Aron",
    "Lairon",
    "Aggron",
    "Meditite",
    "Medicham",
    "Electrike",
    "Manectric",
    "Plusle",
    "Minun",
    "Volbeat",
    "Illumise",
    "Roselia",
    "Gulpin",
    "Swalot",
    "Carvanha",
    "Sharpedo",
    "Wailmer",
    "Wailord",
    "Numel",
    "Camerupt",
    "Torkoal",
    "Spoink",
    "Grumpig",
    "Spinda",
    "Trapinch",
    "Vibrava",
    "Flygon",
    "Cacnea",
    "Cacturne",
    "Swablu",
    "Altaria",
    "Zangoose",
    "Seviper",
    "Lunatone",
    "Solrock",
    "Barboach",
    "Whiscash",
    "Corphish",
    "Crawdaunt",
    "Baltoy",
    "Claydol",
    "Lileep",
    "Cradily",
    "Anorith",
    "Armaldo",
    "Feebas",
    "Milotic",
    "Castform",
    "Kecleon",
    "Shuppet",
    "Banette",
    "Duskull",
    "Dusclops",
    "Tropius",
    "Chimecho",
    "Absol",
    "Wynaut",
    "Snorunt",
    "Glalie",
    "Spheal",
    "Sealeo",
    "Walrein",
    "Clamperl",
    "Huntail",
    "Gorebyss",
    "Relicanth",
    "Luvdisc",
    "Bagon",
    "Shelgon",
    "Salamence",
    "Beldum",
    "Metang",
    "Metagross",
    "Regirock",
    "Regice",
    "Registeel",
    "Latias",
    "Latios",
    "Kyogre",
    "Groudon",
    "Rayquaza",
    "Jirachi",
    "Deoxys",
    "Turtwig",
    "Grotle",
    "Torterra",
    "Chimchar",
    "Monferno",
    "Infernape",
    "Piplup",
    "Prinplup",
    "Empoleon",
    "Starly",
    "Staravia",
    "Staraptor",
    "Bidoof",
    "Bibarel",
    "Kricketot",
    "Kricketune",
    "Shinx",
    "Luxio",
    "Luxray",
    "Budew",
    "Roserade",
    "Cranidos",
    "Rampardos",
    "Shieldon",
    "Bastiodon",
    "Burmy",
    "Wormadam",
    "Mothim",
    "Combee",
    "Vespiquen",
    "Pachirisu",
    "Buizel",
    "Floatzel",
    "Cherubi",
    "Cherrim",
    "Shellos",
    "Gastrodon",
    "Ambipom",
    "Drifloon",
    "Drifblim",
    "Buneary",
    "Lopunny",
    "Mismagius",
    "Honchkrow",
    "Glameow",
    "Purugly",
    "Chingling",
    "Stunky",
    "Skuntank",
    "Bronzor",
    "Bronzong",
    "Bonsly",
    "Mime Jr.",
    "Happiny",
    "Chatot",
    "Spiritomb",
    "Gible",
    "Gabite",
    "Garchomp",
    "Munchlax",
    "Riolu",
    "Lucario",
    "Hippopotas",
    "Hippowdon",
    "Skorupi",
    "Drapion",
    "Croagunk",
    "Toxicroak",
    "Carnivine",
    "Finneon",
    "Lumineon",
    "Mantyke",
    "Snover",
    "Abomasnow",
    "Weavile",
    "Magnezone",
    "Lickilicky",
    "Rhyperior",
    "Tangrowth",
    "Electivire",
    "Magmortar",
    "Togekiss",
    "Yanmega",
    "Leafeon",
    "Glaceon",
    "Gliscor",
    "Mamoswine",
    "Porygon-Z",
    "Gallade",
    "Probopass",
    "Dusknoir",
    "Froslass",
    "Rotom",
    "Uxie",
    "Mesprit",
    "Azelf",
    "Dialga",
    "Palkia",
    "Heatran",
    "Regigigas",
    "Giratina",
    "Cresselia",
    "Phione",
    "Manaphy",
    "Darkrai",
    "Shaymin",
    "Arceus",
    "Victini",
    "Snivy",
    "Servine",
    "Serperior",
    "Tepig",
    "Pignite",
    "Emboar",
    "Oshawott",
    "Dewott",
    "Samurott",
    "Patrat",
    "Watchog",
    "Lillipup",
    "Herdier",
    "Stoutland",
    "Purrloin",
    "Liepard",
    "Pansage",
    "Simisage",
    "Pansear",
    "Simisear",
    "Panpour",
    "Simipour",
    "Munna",
    "Musharna",
    "Pidove",
    "Tranquill",
    "Unfezant",
    "Blitzle",
    "Zebstrika",
    "Roggenrola",
    "Boldore",
    "Gigalith",
    "Woobat",
    "Swoobat",
    "Drilbur",
    "Excadrill",
    "Audino",
    "Timburr",
    "Gurdurr",
    "Conkeldurr",
    "Tympole",
    "Palpitoad",
    "Seismitoad",
    "Throh",
    "Sawk",
    "Sewaddle",
    "Swadloon",
    "Leavanny",
    "Venipede",
    "Whirlipede",
    "Scolipede",
    "Cottonee",
    "Whimsicott",
    "Petilil",
    "Lilligant",
    "Basculin",
    "Sandile",
    "Krokorok",
    "Krookodile",
    "Darumaka",
    "Darmanitan",
    "Maractus",
    "Dwebble",
    "Crustle",
    "Scraggy",
    "Scrafty",
    "Sigilyph",
    "Yamask",
    "Cofagrigus",
    "Tirtouga",
    "Carracosta",
    "Archen",
    "Archeops",
    "Trubbish",
    "Garbodor",
    "Zorua",
    "Zoroark",
    "Minccino",
    "Cinccino",
    "Gothita",
    "Gothorita",
    "Gothitelle",
    "Solosis",
    "Duosion",
    "Reuniclus",
    "Ducklett",
    "Swanna",
    "Vanillite",
    "Vanillish",
    "Vanilluxe",
    "Deerling",
    "Sawsbuck",
    "Emolga",
    "Karrablast",
    "Escavalier",
    "Foongus",
    "Amoonguss",
    "Frillish",
    "Jellicent",
    "Alomomola",
    "Joltik",
    "Galvantula",
    "Ferroseed",
    "Ferrothorn",
    "Klink",
    "Klang",
    "Klinklang",
    "Tynamo",
    "Eelektrik",
    "Eelektross",
    "Elgyem",
    "Beheeyem",
    "Litwick",
    "Lampent",
    "Chandelure",
    "Axew",
    "Fraxure",
    "Haxorus",
    "Cubchoo",
    "Beartic",
    "Cryogonal",
    "Shelmet",
    "Accelgor",
    "Stunfisk",
    "Mienfoo",
    "Mienshao",
    "Druddigon",
    "Golett",
    "Golurk",
    "Pawniard",
    "Bisharp",
    "Bouffalant",
    "Rufflet",
    "Braviary",
    "Vullaby",
    "Mandibuzz",
    "Heatmor",
    "Durant",
    "Deino",
    "Zweilous",
    "Hydreigon",
    "Larvesta",
    "Volcarona",
    "Cobalion",
    "Terrakion",
    "Virizion",
    "Tornadus",
    "Thundurus",
    "Reshiram",
    "Zekrom",
    "Landorus",
    "Kyurem",
    "Keldeo",
    "Meloetta",
    "Genesect",
    "Chespin",
    "Quilladin",
    "Chesnaught",
    "Fennekin",
    "Braixen",
    "Delphox",
    "Froakie",
    "Frogadier",
    "Greninja",
    "Bunnelby",
    "Diggersby",
    "Fletchling",
    "Fletchinder",
    "Talonflame",
    "Scatterbug",
    "Spewpa",
    "Vivillon",
    "Litleo",
    "Pyroar",
    "Flabébé",
    "Floette",
    "Florges",
    "Skiddo",
    "Gogoat",
    "Pancham",
    "Pangoro",
    "Furfrou",
    "Espurr",
    "Meowstic",
    "Honedge",
    "Doublade",
    "Aegislash",
    "Spritzee",
    "Aromatisse",
    "Swirlix",
    "Slurpuff",
    "Inkay",
    "Malamar",
    "Binacle",
    "Barbaracle",
    "Skrelp",
    "Dragalge",
    "Clauncher",
    "Clawitzer",
    "Helioptile",
    "Heliolisk",
    "Tyrunt",
    "Tyrantrum",
    "Amaura",
    "Aurorus",
    "Sylveon",
    "Hawlucha",
    "Dedenne",
    "Carbink",
    "Goomy",
    "Sliggoo",
    "Goodra",
    "Klefki",
    "Phantump",
    "Trevenant",
    "Pumpkaboo",
    "Gourgeist",
    "Bergmite",
    "Avalugg",
    "Noibat",
    "Noivern",
    "Xerneas",
    "Yveltal",
    "Zygarde",
    "Diancie",
    "Hoopa",
    "Volcanion",
    "Rowlet",
    "Dartrix",
    "Decidueye",
    "Litten",
    "Torracat",
    "Incineroar",
    "Popplio",
    "Brionne",
    "Primarina",
    "Pikipek",
    "Trumbeak",
    "Toucannon",
    "Yungoos",
    "Gumshoos",
    "Grubbin",
    "Charjabug",
    "Vikavolt",
    "Crabrawler",
    "Crabominable",
    "Oricorio",
    "Cutiefly",
    "Ribombee",
    "Rockruff",
    "Lycanroc",
    "Wishiwashi",
    "Mareanie",
    "Toxapex",
    "Mudbray",
    "Mudsdale",
    "Dewpider",
    "Araquanid",
    "Fomantis",
    "Lurantis",
    "Morelull",
    "Shiinotic",
    "Salandit",
    "Salazzle",
    "Stufful",
    "Bewear",
    "Bounsweet",
    "Steenee",
    "Tsareena",
    "Comfey",
    "Oranguru",
    "Passimian",
    "Wimpod",
    "Golisopod",
    "Sandygast",
    "Palossand",
    "Pyukumuku",
    "Type: Null",
    "Silvally",
    "Minior",
    "Komala",
    "Turtonator",
    "Togedemaru",
    "Mimikyu",
    "Bruxish",
    "Drampa",
    "Dhelmise",
    "Jangmo-o",
    "Hakamo-o",
    "Kommo-o",
    "Tapu Koko",
    "Tapu Lele",
    "Tapu Bulu",
    "Tapu Fini",
    "Cosmog",
    "Cosmoem",
    "Solgaleo",
    "Lunala",
    "Nihilego",
    "Buzzwole",
    "Pheromosa",
    "Xurkitree",
    "Celesteela",
    "Kartana",
    "Guzzlord",
    "Necrozma",
    "Magearna",
    "Marshadow",
    "Poipole",
    "Naganadel",
    "Stakataka",
    "Blacephalon",
    "Zeraora"
};

enum regions
{
    KANTO,
    JOHTO,
    HOENN,
    SINNOH,
    UNOVA,
    KALOS,
    ALOLA
};

enum pokemonTypes
{
    NORMAL,
    FIRE,
    WATER,
    ELECTRIC,
    GRASS,
    ICE,
    FIGHTING,
    POISON,
    GROUND,
    FLYING,
    PSYCHIC,
    BUG,
    ROCK,
    GHOST,
    DRAGON,
    DARK,
    STEEL,
    FAIRY,
    VARIABLE_FORM,
    NONE
};

struct typings
{
    pokemonTypes type;
    pokemonTypes subType;
};

std::vector<typings> pokemonTypingVec
{
    /*KANTO*/
    {GRASS, POISON},
    {GRASS, POISON},
    {GRASS, POISON},
    {FIRE, NONE},
    {FIRE, NONE},
    {FIRE, FLYING},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {BUG, NONE},
    {BUG, NONE},
    {BUG, FLYING},
    {BUG, POISON},
    {BUG, POISON},
    {BUG, POISON},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {POISON, NONE},
    {POISON, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {GROUND, NONE},
    {GROUND, NONE},
    {POISON, NONE},
    {POISON, NONE},
    {POISON, GROUND},
    {POISON, NONE},
    {POISON, NONE},
    {POISON, GROUND},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {FIRE, NONE},
    {FIRE, NONE},
    {NORMAL, FAIRY},
    {NORMAL, FAIRY},
    {POISON, FLYING},
    {POISON, FLYING},
    {GRASS, POISON},
    {GRASS, POISON},
    {GRASS, POISON},
    {BUG, GRASS},
    {BUG, GRASS},
    {BUG, POISON},
    {BUG, POISON},
    {GROUND, NONE},
    {GROUND, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {FIRE, NONE},
    {FIRE, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, FIGHTING},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {GRASS, POISON},
    {GRASS, POISON},
    {GRASS, POISON},
    {WATER, POISON},
    {WATER, POISON},
    {ROCK, GROUND},
    {ROCK, GROUND},
    {ROCK, GROUND},
    {FIRE, NONE},
    {FIRE, NONE},
    {WATER, PSYCHIC},
    {WATER, PSYCHIC},
    {ELECTRIC, STEEL},
    {ELECTRIC, STEEL},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {WATER, NONE},
    {WATER, ICE},
    {POISON, NONE},
    {POISON, NONE},
    {WATER, NONE},
    {WATER, ICE},
    {GHOST, POISON},
    {GHOST, POISON},
    {GHOST, POISON},
    {ROCK, GROUND},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {GRASS, PSYCHIC},
    {GRASS, PSYCHIC},
    {GROUND, NONE},
    {GROUND, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {NORMAL, NONE},
    {POISON, NONE},
    {POISON, NONE},
    {GROUND, ROCK},
    {GROUND, ROCK},
    {NORMAL, NONE},
    {GRASS, NONE},
    {NORMAL, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, PSYCHIC},
    {PSYCHIC, FAIRY},
    {BUG, FLYING},
    {ICE, PSYCHIC},
    {ELECTRIC, NONE},
    {FIRE, NONE},
    {BUG, NONE},
    {NORMAL, NONE},
    {WATER, NONE},
    {WATER, FLYING},
    {WATER, ICE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {WATER, NONE},
    {ELECTRIC, NONE},
    {FIRE, NONE},
    {NORMAL, NONE},
    {ROCK, WATER},
    {ROCK, WATER},
    {ROCK, WATER},
    {ROCK, WATER},
    {ROCK, FLYING},
    {NORMAL, NONE},
    {ICE, FLYING},
    {ELECTRIC, FLYING},
    {FIRE, FLYING},
    {DRAGON, NONE},
    {DRAGON, NONE},
    {DRAGON, FLYING},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},

    /*JOHTO*/
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {FIRE, NONE},
    {FIRE, NONE},
    {FIRE, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {BUG, FLYING},
    {BUG, FLYING},
    {BUG, POISON},
    {BUG, POISON},
    {POISON, FLYING},
    {WATER, ELECTRIC},
    {WATER, ELECTRIC},
    {ELECTRIC, NONE},
    {FAIRY, NONE},
    {NORMAL, FAIRY},
    {FAIRY, NONE},
    {FAIRY, FLYING},
    {PSYCHIC, FLYING},
    {PSYCHIC, FLYING},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {GRASS, NONE},
    {WATER, FAIRY},
    {WATER, FAIRY},
    {ROCK, NONE},
    {WATER, NONE},
    {GRASS, FLYING},
    {GRASS, FLYING},
    {GRASS, FLYING},
    {NORMAL, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {BUG, FLYING},
    {WATER, GROUND},
    {WATER, GROUND},
    {PSYCHIC, NONE},
    {DARK, NONE},
    {DARK, FLYING},
    {WATER, PSYCHIC},
    {GHOST, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {NORMAL, PSYCHIC},
    {BUG, NONE},
    {BUG, STEEL},
    {NORMAL, NONE},
    {GROUND, FLYING},
    {STEEL, GROUND},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {WATER, POISON},
    {BUG, STEEL},
    {BUG, ROCK},
    {BUG, FIGHTING},
    {DARK, ICE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {FIRE, NONE},
    {FIRE, ROCK},
    {ICE, GROUND},
    {ICE, GROUND},
    {WATER, ROCK},
    {WATER, NONE},
    {WATER, NONE},
    {ICE, FLYING},
    {WATER, FLYING},
    {STEEL, FLYING},
    {DARK, FIRE},
    {DARK, FIRE},
    {WATER, DRAGON},
    {GROUND, NONE},
    {GROUND, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {ICE, PSYCHIC},
    {ELECTRIC, NONE},
    {FIRE, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {ELECTRIC, NONE},
    {FIRE, NONE},
    {WATER, NONE},
    {ROCK, GROUND},
    {ROCK, GROUND},
    {ROCK, DARK},
    {PSYCHIC, FLYING},
    {FIRE, FLYING},
    {PSYCHIC, GRASS},

    /*HOENN*/
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {FIRE, NONE},
    {FIRE, FIGHTING},
    {FIRE, FIGHTING},
    {WATER, NONE},
    {WATER, GROUND},
    {WATER, GROUND},
    {DARK, NONE},
    {DARK, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {BUG, NONE},
    {BUG, NONE},
    {BUG, FLYING},
    {BUG, NONE},
    {BUG, POISON},
    {WATER, GRASS},
    {WATER, GRASS},
    {WATER, GRASS},
    {GRASS, NONE},
    {GRASS, DARK},
    {GRASS, DARK},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {WATER, FLYING},
    {WATER, FLYING},
    {PSYCHIC, FAIRY},
    {PSYCHIC, FAIRY},
    {PSYCHIC, FAIRY},
    {BUG, WATER},
    {BUG, FLYING},
    {GRASS, NONE},
    {GRASS, FIGHTING},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {BUG, GROUND},
    {BUG, FLYING},
    {BUG, GHOST},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {NORMAL, FAIRY},
    {ROCK, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {DARK, GHOST},
    {STEEL, FAIRY},
    {STEEL, ROCK},
    {STEEL, ROCK},
    {STEEL, ROCK},
    {FIGHTING, PSYCHIC},
    {FIGHTING, PSYCHIC},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {BUG, NONE},
    {BUG, NONE},
    {GRASS, POISON},
    {POISON, NONE},
    {POISON, NONE},
    {WATER, DARK},
    {WATER, DARK},
    {WATER, NONE},
    {WATER, NONE},
    {FIRE, GROUND},
    {FIRE, GROUND},
    {FIRE, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {NORMAL, NONE},
    {GROUND, NONE},
    {GROUND, DRAGON},
    {GROUND, DRAGON},
    {GRASS, NONE},
    {GRASS, DARK},
    {NORMAL, FLYING},
    {DRAGON, FLYING},
    {NORMAL, NONE},
    {POISON, NONE},
    {ROCK, PSYCHIC},
    {ROCK, PSYCHIC},
    {WATER, GROUND},
    {WATER, GROUND},
    {WATER, NONE},
    {WATER, DARK},
    {GROUND, PSYCHIC},
    {GROUND, PSYCHIC},
    {ROCK, GRASS},
    {ROCK, GRASS},
    {ROCK, BUG},
    {ROCK, BUG},
    {WATER, NONE},
    {WATER, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {GHOST, NONE},
    {GHOST, NONE},
    {GHOST, NONE},
    {GHOST, NONE},
    {GRASS, FLYING},
    {PSYCHIC, NONE},
    {DARK, NONE},
    {PSYCHIC, NONE},
    {ICE, NONE},
    {ICE, NONE},
    {ICE, WATER},
    {ICE, WATER},
    {ICE, WATER},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, ROCK},
    {WATER, NONE},
    {DRAGON, NONE},
    {DRAGON, NONE},
    {DRAGON, FLYING},
    {STEEL, PSYCHIC},
    {STEEL, PSYCHIC},
    {STEEL, PSYCHIC},
    {ROCK, NONE},
    {ICE, NONE},
    {STEEL, NONE},
    {DRAGON, PSYCHIC},
    {DRAGON, PSYCHIC},
    {WATER, NONE},
    {GROUND, NONE},
    {DRAGON, FLYING},
    {STEEL, PSYCHIC},
    {PSYCHIC, NONE},

    /*SINNOH*/
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, GROUND},
    {FIRE, NONE},
    {FIRE, FIGHTING},
    {FIRE, FIGHTING},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, STEEL},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, NONE},
    {NORMAL, WATER},
    {BUG, NONE},
    {BUG, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {GRASS, POISON},
    {GRASS, POISON},
    {ROCK, NONE},
    {ROCK, NONE},
    {ROCK, STEEL},
    {ROCK, STEEL},
    {BUG, NONE},
    {BUG, VARIABLE_FORM},
    {BUG, FLYING},
    {BUG, FLYING},
    {BUG, FLYING},
    {ELECTRIC, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {WATER, NONE},
    {WATER, GROUND},
    {NORMAL, NONE},
    {GHOST, FLYING},
    {GHOST, FLYING},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {GHOST, NONE},
    {DARK, FLYING},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {PSYCHIC, NONE},
    {POISON, DARK},
    {POISON, DARK},
    {STEEL, PSYCHIC},
    {STEEL, PSYCHIC},
    {ROCK, NONE},
    {PSYCHIC, FAIRY},
    {NORMAL, NONE},
    {NORMAL, FLYING},
    {GHOST, DARK},
    {DRAGON, GROUND},
    {DRAGON, GROUND},
    {DRAGON, GROUND},
    {NORMAL, NONE},
    {FIGHTING, NONE},
    {FIGHTING, STEEL},
    {GROUND, NONE},
    {GROUND, NONE},
    {POISON, BUG},
    {POISON, DARK},
    {POISON, FIGHTING},
    {POISON, FIGHTING},
    {GRASS, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, FLYING},
    {GRASS, ICE},
    {GRASS, ICE},
    {DARK, ICE},
    {ELECTRIC, STEEL},
    {NORMAL, NONE},
    {GROUND, ROCK},
    {GRASS, NONE},
    {ELECTRIC, NONE},
    {FIRE, NONE},
    {FAIRY, FLYING},
    {BUG, FLYING},
    {GRASS, NONE},
    {ICE, NONE},
    {GROUND, FLYING},
    {ICE, GROUND},
    {NORMAL, NONE},
    {PSYCHIC, FIGHTING},
    {ROCK, STEEL},
    {GHOST, NONE},
    {ICE, GHOST},
    {ELECTRIC, VARIABLE_FORM},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {STEEL, DRAGON},
    {WATER, DRAGON},
    {FIRE, STEEL},
    {NORMAL, NONE},
    {GHOST, DRAGON},
    {PSYCHIC, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {DARK, NONE},
    {GRASS, VARIABLE_FORM},
    {NORMAL, NONE},

    /*UNOVA*/
    {PSYCHIC, FIRE},
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {FIRE, NONE},
    {FIRE, FIGHTING},
    {FIRE, FIGHTING},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {DARK, NONE},
    {DARK, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {FIRE, NONE},
    {FIRE, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {ROCK, NONE},
    {ROCK, NONE},
    {ROCK, NONE},
    {PSYCHIC, FLYING},
    {PSYCHIC, FLYING},
    {GROUND, NONE},
    {GROUND, STEEL},
    {NORMAL, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {WATER, NONE},
    {WATER, GROUND},
    {WATER, GROUND},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {BUG, GRASS},
    {BUG, GRASS},
    {BUG, GRASS},
    {BUG, POISON},
    {BUG, POISON},
    {BUG, POISON},
    {GRASS, FAIRY},
    {GRASS, FAIRY},
    {GRASS, NONE},
    {GRASS, NONE},
    {WATER, NONE},
    {GROUND, DARK},
    {GROUND, DARK},
    {GROUND, DARK},
    {FIRE, NONE},
    {FIRE, VARIABLE_FORM},
    {GRASS, NONE},
    {BUG, ROCK},
    {BUG, ROCK},
    {DARK, FIGHTING},
    {DARK, FIGHTING},
    {PSYCHIC, FLYING},
    {GHOST, NONE},
    {GHOST, NONE},
    {WATER, ROCK},
    {WATER, ROCK},
    {ROCK, FLYING},
    {ROCK, FLYING},
    {POISON, NONE},
    {POISON, NONE},
    {DARK, NONE},
    {DARK, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {WATER, FLYING},
    {WATER, FLYING},
    {ICE, NONE},
    {ICE, NONE},
    {ICE, NONE},
    {NORMAL, GRASS},
    {NORMAL, GRASS},
    {ELECTRIC, FLYING},
    {BUG, NONE},
    {BUG, STEEL},
    {GRASS, POISON},
    {GRASS, POISON},
    {WATER, GHOST},
    {WATER, GHOST},
    {WATER, NONE},
    {BUG, ELECTRIC},
    {BUG, ELECTRIC},
    {GRASS, STEEL},
    {GRASS, STEEL},
    {STEEL, NONE},
    {STEEL, NONE},
    {STEEL, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {GHOST, FIRE},
    {GHOST, FIRE},
    {GHOST, FIRE},
    {DRAGON, NONE},
    {DRAGON, NONE},
    {DRAGON, NONE},
    {ICE, NONE},
    {ICE, NONE},
    {ICE, NONE},
    {BUG, NONE},
    {BUG, NONE},
    {GROUND, ELECTRIC},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {DRAGON, NONE},
    {GROUND, GHOST},
    {GROUND, GHOST},
    {DARK, STEEL},
    {DARK, STEEL},
    {NORMAL, NONE},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {DARK, FLYING},
    {DARK, FLYING},
    {FIRE, NONE},
    {BUG, STEEL},
    {DARK, DRAGON},
    {DARK, DRAGON},
    {DARK, DRAGON},
    {BUG, FIRE},
    {BUG, FIRE},
    {STEEL, FIGHTING},
    {ROCK, FIGHTING},
    {GRASS, FIGHTING},
    {FLYING, NONE},
    {ELECTRIC, FLYING},
    {DRAGON, FIRE},
    {DRAGON, ELECTRIC},
    {GROUND, FLYING},
    {DRAGON, ICE},
    {WATER, FIGHTING},
    {NORMAL, VARIABLE_FORM},
    {BUG, STEEL},

    /*KALOS*/
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, FIGHTING},
    {FIRE, NONE},
    {FIRE, NONE},
    {FIRE, PSYCHIC},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, DARK},
    {NORMAL, NONE},
    {NORMAL, GROUND},
    {NORMAL, FLYING},
    {FIRE, FLYING},
    {FIRE, FLYING},
    {BUG, NONE},
    {BUG, NONE},
    {BUG, FLYING},
    {FIRE, NORMAL},
    {FIRE, NORMAL},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {FIGHTING, NONE},
    {FIGHTING, DARK},
    {NORMAL, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {STEEL, GHOST},
    {STEEL, GHOST},
    {STEEL, GHOST},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {DARK, PSYCHIC},
    {DARK, PSYCHIC},
    {ROCK, WATER},
    {ROCK, WATER},
    {POISON, WATER},
    {POISON, DRAGON},
    {WATER, NONE},
    {WATER, NONE},
    {ELECTRIC, NORMAL},
    {ELECTRIC, NORMAL},
    {ROCK, DRAGON},
    {ROCK, DRAGON},
    {ROCK, ICE},
    {ROCK, ICE},
    {FAIRY, NONE},
    {FIGHTING, FLYING},
    {ELECTRIC, FAIRY},
    {ROCK, FAIRY},
    {DRAGON, NONE},
    {DRAGON, NONE},
    {DRAGON, NONE},
    {STEEL, FAIRY},
    {GHOST, GRASS},
    {GHOST, GRASS},
    {GHOST, GRASS},
    {GHOST, GRASS},
    {ICE, NONE},
    {ICE, NONE},
    {FLYING, DRAGON},
    {FLYING, DRAGON},
    {FAIRY, NONE},
    {DARK, FLYING},
    {DRAGON, GROUND},
    {ROCK, FAIRY},
    {PSYCHIC, VARIABLE_FORM},
    {FIRE, WATER},

    /*ALOLA*/
    {GRASS, FLYING},
    {GRASS, FLYING},
    {GRASS, GHOST},
    {FIRE, NONE},
    {FIRE, NONE},
    {FIRE, DARK},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, FAIRY},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {BUG, NONE},
    {BUG, ELECTRIC},
    {BUG, ELECTRIC},
    {FIGHTING, NONE},
    {FIGHTING, ICE},
    {VARIABLE_FORM, FLYING},
    {BUG, FAIRY},
    {BUG, FAIRY},
    {ROCK, NONE},
    {ROCK, NONE},
    {WATER, NONE},
    {POISON, WATER},
    {POISON, WATER},
    {GROUND, NONE},
    {GROUND, NONE},
    {WATER, BUG},
    {WATER, BUG},
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, FAIRY},
    {GRASS, FAIRY},
    {POISON, FIRE},
    {POISON, FIRE},
    {NORMAL, FIGHTING},
    {NORMAL, FIGHTING},
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {FAIRY, NONE},
    {NORMAL, PSYCHIC},
    {FIGHTING, NONE},
    {BUG, WATER},
    {BUG, WATER},
    {GHOST, GROUND},
    {GHOST, GROUND},
    {WATER, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {ROCK, FLYING},
    {NORMAL, NONE},
    {FIRE, DRAGON},
    {ELECTRIC, STEEL},
    {GHOST, FAIRY},
    {WATER, PSYCHIC},
    {NORMAL, DRAGON},
    {GHOST, GRASS},
    {DRAGON, NONE},
    {DRAGON, FIGHTING},
    {DRAGON, FIGHTING},
    {ELECTRIC, FAIRY},
    {PSYCHIC, FAIRY},
    {GRASS, FAIRY},
    {WATER, FAIRY},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, STEEL},
    {PSYCHIC, GHOST},
    {ROCK, POISON},
    {BUG, FIGHTING},
    {BUG, FIGHTING},
    {ELECTRIC, NONE},
    {STEEL, FLYING},
    {GRASS, STEEL},
    {DARK, DRAGON},
    {PSYCHIC, NONE},
    {STEEL, FAIRY},
    {FIGHTING, GHOST},
    {POISON, NONE},
    {POISON, DRAGON},
    {ROCK, STEEL},
    {FIRE, GHOST},
    {ELECTRIC, NONE}
};

enum evolutionStages
{
    UNEVOLVED,
    FIRST,
    SECOND
};

std::vector<evolutionStages> evolutionStageVec
{
    /*KANTO*/
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    FIRST,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,

    /*JOHTO*/
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    SECOND,
    FIRST,
    SECOND,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    FIRST,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,

    /*HOENN*/
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,

    /*SINNOH*/
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    FIRST,
    SECOND,
    FIRST,
    SECOND,
    FIRST,
    SECOND,
    SECOND,
    SECOND,
    FIRST,
    FIRST,
    FIRST,
    FIRST,
    SECOND,
    SECOND,
    SECOND,
    FIRST,
    SECOND,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,

    /*UNOVA*/
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,

    /*KALOS*/
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,

    /*ALOLA*/
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED 
};

std::vector<unsigned short> legendaryIndicesVec
{
    143,
    144,
    145,
    149,
    150,
    242,
    243,
    244,
    248,
    249,
    250,
    376,
    377,
    378,
    379,
    380,
    381,
    382,
    383,
    384,
    385,
    479,
    480,
    481,
    482,
    483,
    484,
    485,
    486,
    487,
    488,
    489,
    490,
    491,
    492,
    493,
    637,
    638,
    639,
    640,
    641,
    642,
    643,
    644,
    645,
    646,
    647,
    648,
    715,
    716,
    717,
    718,
    719,
    720,
    771,
    772,
    784,
    785,
    786,
    787,
    788,
    789,
    790,
    791,
    799,
    800,
    801,
    806
};

std::vector<unsigned short> mythicalIndicesVec
{
    150,
    250,
    384,
    385,
    488,
    489,
    490,
    491,
    492,
    493,
    646,
    647,
    648,
    718,
    719,
    720,
    800,
    801,
    806
};

std::vector<unsigned short> starterIndicesVec
{
    0, 3, 6,
    151, 154, 157,
    251, 254, 257,
    386, 389, 392,
    494, 497, 500,
    649, 652, 655,
    721, 724, 727
};

std::vector<unsigned short> genderlessIndicesVec
{
    80,
    81,
    99,
    100,
    119,
    120,
    131,
    136,
    143,
    144,
    145,
    149,
    150,
    200,
    232,
    242,
    243,
    244,
    248,
    249,
    250,
    291,
    336,
    227,
    342,
    343,
    373,
    374,
    375,
    376,
    377,
    378,
    381,
    382,
    383,
    384,
    385,
    435,
    436,
    461,
    473,
    478,
    479,
    480,
    481,
    482,
    483,
    485,
    486,
    488,
    489,
    490,
    491,
    492,
    493,
    598,
    599,
    600,
    614,
    621,
    622,
    637,
    638,
    639,
    642,
    643,
    645,
    646,
    647,
    648,
    702,
    715,
    716,
    717,
    718,
    719,
    720,
    771,
    772,
    773,
    784,
    785,
    786,
    787,
    788,
    789,
    790,
    791,
    792,
    793,
    794,
    795,
    796,
    797,
    798,
    799,
    800,
    801,
    802,
    803,
    804,
    805,
    806
};

enum evolutionTypes
{
    LEVEL,
    LEVEL_MOVE,
    ITEM,
    TRADE,
    TRADE_ITEM,
    FRIENDSHIP,
    SPECIAL
};

std::map<unsigned short, evolutionTypes> canEvolveByMap
{
    /*KANTO*/
    {0, LEVEL},
    {1, LEVEL},
    {3, LEVEL},
    {4, LEVEL},
    {6, LEVEL},
    {7, LEVEL},
    {9, LEVEL},
    {10, LEVEL},
    {12, LEVEL},
    {13, LEVEL},
    {15, LEVEL},
    {16, LEVEL},
    {18, LEVEL},
    {20, LEVEL},
    {22, LEVEL},
    {24, ITEM},
    {26, LEVEL},
    {28, LEVEL},
    {29, ITEM},
    {31, LEVEL},
    {32, ITEM},
    {34, ITEM},
    {36, ITEM},
    {38, ITEM},
    {40, LEVEL},
    {41, FRIENDSHIP},
    {42, LEVEL},
    {43, ITEM},
    {45, LEVEL},
    {47, LEVEL},
    {49, LEVEL},
    {51, LEVEL},
    {53, LEVEL},
    {55, LEVEL},
    {57, ITEM},
    {59, LEVEL},
    {60, SPECIAL},
    {62, LEVEL},
    {63, TRADE},
    {65, LEVEL},
    {66, TRADE},
    {68, LEVEL},
    {69, ITEM},
    {71, LEVEL},
    {73, LEVEL},
    {74, TRADE},
    {76, LEVEL},
    {78, SPECIAL},
    {80, LEVEL},
    {81, SPECIAL},
    {83, LEVEL},
    {85, LEVEL},
    {87, LEVEL},
    {89, ITEM},
    {91, LEVEL},
    {92, TRADE},
    {94, TRADE_ITEM},
    {95, LEVEL},
    {97, LEVEL},
    {99, LEVEL},
    {101, ITEM},
    {103, LEVEL},
    {107, LEVEL_MOVE},
    {108, LEVEL},
    {110, LEVEL},
    {111, TRADE_ITEM},
    {112, FRIENDSHIP},
    {113, LEVEL_MOVE},
    {115, LEVEL},
    {116, TRADE_ITEM},
    {117, LEVEL},
    {119, LEVEL},
    {122, TRADE_ITEM},
    {124, TRADE_ITEM},
    {125, TRADE_ITEM},
    {128, LEVEL},
    {132, SPECIAL},
    {136, TRADE_ITEM},
    {137, LEVEL},
    {139, LEVEL},
    {146, LEVEL},
    {147, LEVEL},

    /*JOHTO*/
    {151, LEVEL},
    {152, LEVEL},
    {154, LEVEL},
    {155, LEVEL},
    {157, LEVEL},
    {158, LEVEL},
    {160, LEVEL},
    {162, LEVEL},
    {164, LEVEL},
    {166, LEVEL},
    {169, LEVEL},
    {171, FRIENDSHIP},
    {172, FRIENDSHIP},
    {173, FRIENDSHIP},
    {174, FRIENDSHIP},
    {175, ITEM},
    {176, LEVEL},
    {178, LEVEL},
    {179, LEVEL},
    {182, LEVEL},
    {186, LEVEL},
    {187, LEVEL},
    {189, LEVEL_MOVE},
    {190, ITEM},
    {192, LEVEL_MOVE},
    {193, LEVEL},
    {197, ITEM},
    {199, ITEM},
    {203, LEVEL},
    {206, SPECIAL},
    {208, LEVEL},
    {214, SPECIAL},
    {215, LEVEL},
    {217, LEVEL},
    {219, LEVEL},
    {220, LEVEL_MOVE},
    {222, LEVEL},
    {227, LEVEL},
    {230, LEVEL},
    {232, TRADE_ITEM},
    {235, SPECIAL},
    {237, LEVEL},
    {238, LEVEL},
    {239, LEVEL},
    {245, LEVEL},
    {246, LEVEL},

    /*HOENN*/
    {251, LEVEL},
    {252, LEVEL},
    {254, LEVEL},
    {255, LEVEL},
    {257, LEVEL},
    {258, LEVEL},
    {260, LEVEL},
    {262, LEVEL},
    {264, LEVEL},
    {265, LEVEL},
    {267, LEVEL},
    {270, LEVEL},
    {271, LEVEL},
    {272, LEVEL},
    {273, LEVEL},
    {275, LEVEL},
    {278, LEVEL},
    {279, LEVEL},
    {280, SPECIAL},
    {282, LEVEL},
    {284, LEVEL},
    {286, LEVEL},
    {287, LEVEL},
    {289, LEVEL},
    {292, LEVEL},
    {293, LEVEL},
    {295, LEVEL},
    {297, FRIENDSHIP},
    {298, SPECIAL},
    {299, LEVEL},
    {303, LEVEL},
    {304, LEVEL},
    {306, LEVEL},
    {308, LEVEL},
    {314, ITEM},
    {315, LEVEL},
    {317, LEVEL},
    {319, LEVEL},
    {321, LEVEL},
    {324, LEVEL},
    {327, LEVEL},
    {328, LEVEL},
    {330, LEVEL},
    {332, LEVEL},
    {338, LEVEL},
    {340, LEVEL},
    {342, LEVEL},
    {344, LEVEL},
    {346, LEVEL},
    {348, TRADE_ITEM},
    {352, LEVEL},
    {354, LEVEL},
    {355, TRADE_ITEM},
    {359, LEVEL},
    {360, SPECIAL},
    {362, LEVEL},
    {363, LEVEL},
    {365, TRADE_ITEM},
    {370, LEVEL},
    {371, LEVEL},
    {373, LEVEL},
    {374, LEVEL},

    /*SINNOH*/
    {386, LEVEL},
    {387, LEVEL},
    {389, LEVEL},
    {390, LEVEL},
    {392, LEVEL},
    {393, LEVEL},
    {395, LEVEL},
    {396, LEVEL},
    {398, LEVEL},
    {400, LEVEL},
    {402, LEVEL},
    {403, LEVEL},
    {405, SPECIAL},
    {407, LEVEL},
    {409, LEVEL},
    {411, SPECIAL},
    {414, SPECIAL},
    {417, LEVEL},
    {419, LEVEL},
    {421, LEVEL},
    {424, LEVEL},
    {426, LEVEL},
    {430, LEVEL},
    {432, SPECIAL},
    {433, LEVEL},
    {435, LEVEL},
    {437, LEVEL_MOVE},
    {438, LEVEL_MOVE},
    {439, SPECIAL},
    {442, LEVEL},
    {443, LEVEL},
    {445, FRIENDSHIP},
    {446, SPECIAL},
    {448, LEVEL},
    {450, LEVEL},
    {452, LEVEL},
    {455, LEVEL},
    {457, SPECIAL},
    {458, LEVEL},

    /*UNOVA*/
    {494, LEVEL},
    {495, LEVEL},
    {497, LEVEL},
    {498, LEVEL},
    {500, LEVEL},
    {501, LEVEL},
    {503, LEVEL},
    {505, LEVEL},
    {506, LEVEL},
    {508, LEVEL},
    {510, LEVEL},
    {512, LEVEL},
    {514, LEVEL},
    {516, LEVEL},
    {518, LEVEL},
    {519, LEVEL},
    {521, LEVEL},
    {523, LEVEL},
    {524, TRADE},
    {526, FRIENDSHIP},
    {528, LEVEL},
    {531, LEVEL},
    {532, TRADE},
    {534, LEVEL},
    {535, LEVEL},
    {539, LEVEL},
    {540, FRIENDSHIP},
    {542, LEVEL},
    {543, LEVEL},
    {545, ITEM},
    {547, ITEM},
    {550, LEVEL},
    {551, LEVEL},
    {553, LEVEL},
    {556, LEVEL},
    {558, LEVEL},
    {561, LEVEL},
    {563, LEVEL},
    {565, LEVEL},
    {567, LEVEL},
    {569, LEVEL},
    {571, ITEM},
    {573, LEVEL},
    {574, LEVEL},
    {576, LEVEL},
    {577, LEVEL},
    {579, LEVEL},
    {581, LEVEL},
    {582, LEVEL},
    {584, LEVEL},
    {587, SPECIAL},
    {589, LEVEL},
    {591, LEVEL},
    {594, LEVEL},
    {596, LEVEL},
    {598, LEVEL},
    {599, LEVEL},
    {601, LEVEL},
    {602, ITEM},
    {604, LEVEL},
    {606, LEVEL},
    {607, ITEM},
    {609, LEVEL},
    {610, LEVEL},
    {612, LEVEL},
    {615, SPECIAL},
    {618, LEVEL},
    {621, LEVEL},
    {623, LEVEL},
    {626, LEVEL},
    {628, LEVEL},
    {632, LEVEL},
    {633, LEVEL},
    {635, LEVEL},

    /*KALOS*/
    {649, LEVEL},
    {650, LEVEL},
    {652, LEVEL},
    {653, LEVEL},
    {655, LEVEL},
    {656, LEVEL},
    {658, LEVEL},
    {660, LEVEL},
    {661, LEVEL},
    {663, LEVEL},
    {664, LEVEL},
    {666, LEVEL},
    {668, LEVEL},
    {669, ITEM},
    {671, LEVEL},
    {673, LEVEL},
    {676, LEVEL},
    {678, LEVEL},
    {679, ITEM},
    {681, TRADE_ITEM},
    {683, TRADE_ITEM},
    {685, SPECIAL},
    {687, LEVEL},
    {689, LEVEL},
    {691, LEVEL},
    {693, ITEM},
    {695, SPECIAL},
    {697, SPECIAL},
    {703, LEVEL},
    {704, SPECIAL},
    {707, TRADE},
    {709, TRADE},
    {711, LEVEL},
    {713, LEVEL},

    /*ALOLA*/
    {721, LEVEL},
    {722, LEVEL},
    {724, LEVEL},
    {725, LEVEL},
    {727, LEVEL},
    {728, LEVEL},
    {730, LEVEL},
    {731, LEVEL},
    {733, LEVEL},
    {735, LEVEL},
    {736, SPECIAL},
    {738, SPECIAL},
    {741, LEVEL},
    {743, SPECIAL},
    {746, LEVEL},
    {748, LEVEL},
    {750, LEVEL},
    {752, SPECIAL},
    {754, LEVEL},
    {756, SPECIAL},
    {758, LEVEL},
    {760, LEVEL},
    {761, LEVEL_MOVE},
    {766, LEVEL},
    {768, LEVEL},
    {771, FRIENDSHIP},
    {781, LEVEL},
    {782, LEVEL},
    {788, LEVEL},
    {789, LEVEL},
    {802, LEVEL_MOVE}
};

struct canEvolveBy
{
    unsigned short canEvolveIndex;
    evolutionTypes evolvesBy;
};

std::vector<canEvolveBy> canEvolveByVec
{
    /*KANTO*/
    {0, LEVEL},
    {1, LEVEL},
    {3, LEVEL},
    {4, LEVEL},
    {6, LEVEL},
    {7, LEVEL},
    {9, LEVEL},
    {10, LEVEL},
    {12, LEVEL},
    {13, LEVEL},
    {15, LEVEL},
    {16, LEVEL},
    {18, LEVEL},
    {20, LEVEL},
    {22, LEVEL},
    {24, ITEM},
    {26, LEVEL},
    {28, LEVEL},
    {29, ITEM},
    {31, LEVEL},
    {32, ITEM},
    {34, ITEM},
    {36, ITEM},
    {38, ITEM},
    {40, LEVEL},
    {41, FRIENDSHIP},
    {42, LEVEL},
    {43, ITEM},
    {45, LEVEL},
    {47, LEVEL},
    {49, LEVEL},
    {51, LEVEL},
    {53, LEVEL},
    {55, LEVEL},
    {57, ITEM},
    {59, LEVEL},
    {60, SPECIAL},
    {62, LEVEL},
    {63, TRADE},
    {65, LEVEL},
    {66, TRADE},
    {68, LEVEL},
    {69, ITEM},
    {71, LEVEL},
    {73, LEVEL},
    {74, TRADE},
    {76, LEVEL},
    {78, SPECIAL},
    {80, LEVEL},
    {81, SPECIAL},
    {83, LEVEL},
    {85, LEVEL},
    {87, LEVEL},
    {89, ITEM},
    {91, LEVEL},
    {92, TRADE},
    {94, TRADE_ITEM},
    {95, LEVEL},
    {97, LEVEL},
    {99, LEVEL},
    {101, ITEM},
    {103, LEVEL},
    {107, LEVEL_MOVE},
    {108, LEVEL},
    {110, LEVEL},
    {111, TRADE_ITEM},
    {112, FRIENDSHIP},
    {113, LEVEL_MOVE},
    {115, LEVEL},
    {116, TRADE_ITEM},
    {117, LEVEL},
    {122, TRADE_ITEM},
    {124, TRADE_ITEM},
    {125, TRADE_ITEM},
    {128, LEVEL},
    {132, SPECIAL},
    {136, TRADE_ITEM},
    {137, LEVEL},
    {139, LEVEL},
    {146, LEVEL},
    {147, LEVEL},

    /*JOHTO*/
    {151, LEVEL},
    {152, LEVEL},
    {154, LEVEL},
    {155, LEVEL},
    {157, LEVEL},
    {158, LEVEL},
    {160, LEVEL},
    {162, LEVEL},
    {164, LEVEL},
    {166, LEVEL},
    {169, LEVEL},
    {171, FRIENDSHIP},
    {172, FRIENDSHIP},
    {173, FRIENDSHIP},
    {174, FRIENDSHIP},
    {175, ITEM},
    {176, LEVEL},
    {178, LEVEL},
    {179, LEVEL},
    {182, LEVEL},
    {186, LEVEL},
    {187, LEVEL},
    {189, LEVEL_MOVE},
    {190, ITEM},
    {192, LEVEL_MOVE},
    {193, LEVEL},
    {197, ITEM},
    {199, ITEM},
    {203, LEVEL},
    {206, SPECIAL},
    {208, LEVEL},
    {214, SPECIAL},
    {215, LEVEL},
    {217, LEVEL},
    {219, LEVEL},
    {220, LEVEL_MOVE},
    {222, LEVEL},
    {227, LEVEL},
    {230, LEVEL},
    {232, TRADE_ITEM},
    {235, SPECIAL},
    {237, LEVEL},
    {238, LEVEL},
    {239, LEVEL},
    {245, LEVEL},
    {246, LEVEL},

    /*HOENN*/
    {251, LEVEL},
    {252, LEVEL},
    {254, LEVEL},
    {255, LEVEL},
    {257, LEVEL},
    {258, LEVEL},
    {260, LEVEL},
    {262, LEVEL},
    {264, LEVEL},
    {265, LEVEL},
    {267, LEVEL},
    {270, LEVEL},
    {271, LEVEL},
    {272, LEVEL},
    {273, LEVEL},
    {275, LEVEL},
    {278, LEVEL},
    {279, LEVEL},
    {280, SPECIAL},
    {282, LEVEL},
    {284, LEVEL},
    {286, LEVEL},
    {287, LEVEL},
    {289, LEVEL},
    {292, LEVEL},
    {293, LEVEL},
    {295, LEVEL},
    {297, FRIENDSHIP},
    {298, SPECIAL},
    {299, LEVEL},
    {303, LEVEL},
    {304, LEVEL},
    {306, LEVEL},
    {308, LEVEL},
    {314, ITEM},
    {315, LEVEL},
    {317, LEVEL},
    {319, LEVEL},
    {321, LEVEL},
    {324, LEVEL},
    {327, LEVEL},
    {328, LEVEL},
    {330, LEVEL},
    {332, LEVEL},
    {338, LEVEL},
    {340, LEVEL},
    {342, LEVEL},
    {344, LEVEL},
    {346, LEVEL},
    {348, TRADE_ITEM},
    {352, LEVEL},
    {354, LEVEL},
    {355, TRADE_ITEM},
    {359, LEVEL},
    {360, SPECIAL},
    {362, LEVEL},
    {363, LEVEL},
    {365, TRADE_ITEM},
    {370, LEVEL},
    {371, LEVEL},
    {373, LEVEL},
    {374, LEVEL},

    /*SINNOH*/
    {386, LEVEL},
    {387, LEVEL},
    {389, LEVEL},
    {390, LEVEL},
    {392, LEVEL},
    {393, LEVEL},
    {395, LEVEL},
    {396, LEVEL},
    {398, LEVEL},
    {400, LEVEL},
    {402, LEVEL},
    {403, LEVEL},
    {405, SPECIAL},
    {407, LEVEL},
    {409, LEVEL},
    {411, SPECIAL},
    {414, SPECIAL},
    {417, LEVEL},
    {419, LEVEL},
    {421, LEVEL},
    {424, LEVEL},
    {426, LEVEL},
    {430, LEVEL},
    {432, SPECIAL},
    {433, LEVEL},
    {435, LEVEL},
    {437, LEVEL_MOVE},
    {438, LEVEL_MOVE},
    {439, SPECIAL},
    {442, LEVEL},
    {443, LEVEL},
    {445, FRIENDSHIP},
    {446, SPECIAL},
    {448, LEVEL},
    {450, LEVEL},
    {452, LEVEL},
    {455, LEVEL},
    {457, SPECIAL},
    {458, LEVEL},

    /*UNOVA*/
    {494, LEVEL},
    {495, LEVEL},
    {497, LEVEL},
    {498, LEVEL},
    {500, LEVEL},
    {501, LEVEL},
    {503, LEVEL},
    {505, LEVEL},
    {506, LEVEL},
    {508, LEVEL},
    {510, LEVEL},
    {512, LEVEL},
    {514, LEVEL},
    {516, LEVEL},
    {518, LEVEL},
    {519, LEVEL},
    {521, LEVEL},
    {523, LEVEL},
    {524, TRADE},
    {526, FRIENDSHIP},
    {528, LEVEL},
    {531, LEVEL},
    {532, TRADE},
    {534, LEVEL},
    {535, LEVEL},
    {539, LEVEL},
    {540, FRIENDSHIP},
    {542, LEVEL},
    {543, LEVEL},
    {545, ITEM},
    {547, ITEM},
    {550, LEVEL},
    {551, LEVEL},
    {553, LEVEL},
    {556, LEVEL},
    {558, LEVEL},
    {561, LEVEL},
    {563, LEVEL},
    {565, LEVEL},
    {567, LEVEL},
    {569, LEVEL},
    {571, ITEM},
    {573, LEVEL},
    {574, LEVEL},
    {576, LEVEL},
    {577, LEVEL},
    {579, LEVEL},
    {581, LEVEL},
    {582, LEVEL},
    {584, LEVEL},
    {587, SPECIAL},
    {589, LEVEL},
    {591, LEVEL},
    {594, LEVEL},
    {596, LEVEL},
    {598, LEVEL},
    {599, LEVEL},
    {601, LEVEL},
    {602, ITEM},
    {604, LEVEL},
    {606, LEVEL},
    {607, ITEM},
    {609, LEVEL},
    {610, LEVEL},
    {612, LEVEL},
    {615, SPECIAL},
    {618, LEVEL},
    {621, LEVEL},
    {623, LEVEL},
    {626, LEVEL},
    {628, LEVEL},
    {632, LEVEL},
    {633, LEVEL},
    {635, LEVEL},

    /*KALOS*/
    {649, LEVEL},
    {650, LEVEL},
    {652, LEVEL},
    {653, LEVEL},
    {655, LEVEL},
    {656, LEVEL},
    {658, LEVEL},
    {660, LEVEL},
    {661, LEVEL},
    {663, LEVEL},
    {664, LEVEL},
    {666, LEVEL},
    {668, LEVEL},
    {669, ITEM},
    {671, LEVEL},
    {673, LEVEL},
    {676, LEVEL},
    {678, LEVEL},
    {679, ITEM},
    {681, TRADE_ITEM},
    {683, TRADE_ITEM},
    {685, SPECIAL},
    {687, LEVEL},
    {689, LEVEL},
    {691, LEVEL},
    {693, ITEM},
    {695, SPECIAL},
    {697, SPECIAL},
    {703, LEVEL},
    {704, SPECIAL},
    {707, TRADE},
    {709, TRADE},
    {711, LEVEL},
    {713, LEVEL},

    /*ALOLA*/
    {721, LEVEL},
    {722, LEVEL},
    {724, LEVEL},
    {725, LEVEL},
    {727, LEVEL},
    {728, LEVEL},
    {730, LEVEL},
    {731, LEVEL},
    {733, LEVEL},
    {735, LEVEL},
    {736, SPECIAL},
    {738, SPECIAL},
    {741, LEVEL},
    {743, SPECIAL},
    {746, LEVEL},
    {748, LEVEL},
    {750, LEVEL},
    {752, SPECIAL},
    {754, LEVEL},
    {756, SPECIAL},
    {758, LEVEL},
    {760, LEVEL},
    {761, LEVEL_MOVE},
    {766, LEVEL},
    {768, LEVEL},
    {771, FRIENDSHIP},
    {781, LEVEL},
    {782, LEVEL},
    {788, LEVEL},
    {789, LEVEL},
    {802, LEVEL_MOVE}
};

enum gender
{
    MALE,
    FEMALE
};

std::map<unsigned short, gender> monoGenderMap
{
    {28, FEMALE},
    {29, FEMALE},
    {30, FEMALE},
    {31, MALE},
    {32, MALE},
    {33, MALE},
    {105, MALE},
    {106, MALE},
    {112, FEMALE},
    {114, FEMALE},
    {123, FEMALE},
    {127, MALE},
    {235, MALE},
    {236, MALE},
    {237, FEMALE},
    {240, FEMALE},
    {241, FEMALE},
    {312, MALE},
    {313, FEMALE},
    {379, FEMALE},
    {380, MALE},
    {439, FEMALE},
    {475, MALE},
    {477, FEMALE},
    {412, FEMALE},
    {413, MALE},
    {415, FEMALE},
    {487, FEMALE},
    {537, MALE},
    {538, MALE},
    {547, FEMALE},
    {548, FEMALE},
    {626, MALE},
    {627, MALE},
    {628, FEMALE},
    {629, FEMALE},
    {640, MALE},
    {641, MALE},
    {644, MALE},
    {668, FEMALE},
    {669, FEMALE},
    {670, FEMALE},
    {757, FEMALE},
    {760, FEMALE},
    {761, FEMALE},
    {762, FEMALE}
};

struct monoGenderData
{
    unsigned short monoGenderIndex;
    gender pokemonGender;
};

std::vector<monoGenderData>  monoGenderVec
{
    {28, FEMALE},
    {29, FEMALE},
    {30, FEMALE},
    {31, MALE},
    {32, MALE},
    {33, MALE},
    {105, MALE},
    {106, MALE},
    {112, FEMALE},
    {114, FEMALE},
    {123, FEMALE},
    {127, MALE},
    {235, MALE},
    {236, MALE},
    {237, FEMALE},
    {240, FEMALE},
    {241, FEMALE},
    {312, MALE},
    {313, FEMALE},
    {379, FEMALE},
    {380, MALE},
    {439, FEMALE},
    {475, MALE},
    {477, FEMALE},
    {412, FEMALE},
    {413, MALE},
    {415, FEMALE},
    {487, FEMALE},
    {537, MALE},
    {538, MALE},
    {547, FEMALE},
    {548, FEMALE},
    {626, MALE},
    {627, MALE},
    {628, FEMALE},
    {629, FEMALE},
    {640, MALE},
    {641, MALE},
    {644, MALE},
    {668, FEMALE},
    {669, FEMALE},
    {670, FEMALE},
    {757, FEMALE},
    {760, FEMALE},
    {761, FEMALE},
    {762, FEMALE}
};