#pragma once
#include <vector>
#include <string>
#include <map>

std::vector<std::string> pokemonNamesVec
{
    "Bulbasaur",
    "Ivysaur",
    "Venusaur",
    "Charmander",
    "Charmeleon",
    "Charizard",
    "Squirtle",
    "Wartortle",
    "Blastoise",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Pidgey",
    "Pidgeotto",
    "Pidgeot",
    "Rattata",
    "Raticate",
    "Spearow",
    "Fearow",
    "Ekans",
    "Arbok",
    "Pikachu",
    "Raichu",
    "Sandshrew",
    "Sandslash",
    "Nidoran♀",
    "Nidorina",
    "Nidoqueen",
    "Nidoran♂",
    "Nidorino",
    "Nidoking",
    "Clefairy",
    "Clefable",
    "Vulpix",
    "Ninetales",
    "Jigglypuff",
    "Wigglytuff",
    "Zubat",
    "Golbat",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Paras",
    "Parasect",
    "Venonat",
    "Venomoth",
    "Diglett",
    "Dugtrio",
    "Meowth",
    "Persian",
    "Psyduck",
    "Golduck",
    "Mankey",
    "Primeape",
    "Growlithe",
    "Arcanine",
    "Poliwag",
    "Poliwhirl",
    "Poliwrath",
    "Abra",
    "Kadabra",
    "Alakazam",
    "Machop",
    "Machoke",
    "Machamp",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Tentacool",
    "Tentacruel",
    "Geodude",
    "Graveler",
    "Golem",
    "Ponyta",
    "Rapidash",
    "Slowpoke",
    "Slowbro",
    "Magnemite",
    "Magneton",
    "Farfetch’d",
    "Doduo",
    "Dodrio",
    "Seel",
    "Dewgong",
    "Grimer",
    "Muk",
    "Shellder",
    "Cloyster",
    "Gastly",
    "Haunter",
    "Gengar",
    "Onix",
    "Drowzee",
    "Hypno",
    "Krabby",
    "Kingler",
    "Voltorb",
    "Electrode",
    "Exeggcute",
    "Exeggutor",
    "Cubone",
    "Marowak",
    "Hitmonlee",
    "Hitmonchan",
    "Lickitung",
    "Koffing",
    "Weezing",
    "Rhyhorn",
    "Rhydon",
    "Chansey",
    "Tangela",
    "Kangaskhan",
    "Horsea",
    "Seadra",
    "Goldeen",
    "Seaking",
    "Staryu",
    "Starmie",
    "Mr. Mime",
    "Scyther",
    "Jynx",
    "Electabuzz",
    "Magmar",
    "Pinsir",
    "Tauros",
    "Magikarp",
    "Gyarados",
    "Lapras",
    "Ditto",
    "Eevee",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Porygon",
    "Omanyte",
    "Omastar",
    "Kabuto",
    "Kabutops",
    "Aerodactyl",
    "Snorlax",
    "Articuno",
    "Zapdos",
    "Moltres",
    "Dratini",
    "Dragonair",
    "Dragonite",
    "Mewtwo",
    "Mew",
    "Chikorita",
    "Bayleef",
    "Meganium",
    "Cyndaquil",
    "Quilava",
    "Typhlosion",
    "Totodile",
    "Croconaw",
    "Feraligatr",
    "Sentret",
    "Furret",
    "Hoothoot",
    "Noctowl",
    "Ledyba",
    "Ledian",
    "Spinarak",
    "Ariados",
    "Crobat",
    "Chinchou",
    "Lanturn",
    "Pichu",
    "Cleffa",
    "Igglybuff",
    "Togepi",
    "Togetic",
    "Natu",
    "Xatu",
    "Mareep",
    "Flaaffy",
    "Ampharos",
    "Bellossom",
    "Marill",
    "Azumarill",
    "Sudowoodo",
    "Politoed",
    "Hoppip",
    "Skiploom",
    "Jumpluff",
    "Aipom",
    "Sunkern",
    "Sunflora",
    "Yanma",
    "Wooper",
    "Quagsire",
    "Espeon",
    "Umbreon",
    "Murkrow",
    "Slowking",
    "Misdreavus",
    "Unown",
    "Wobbuffet",
    "Girafarig",
    "Pineco",
    "Forretress",
    "Dunsparce",
    "Gligar",
    "Steelix",
    "Snubbull",
    "Granbull",
    "Qwilfish",
    "Scizor",
    "Shuckle",
    "Heracross",
    "Sneasel",
    "Teddiursa",
    "Ursaring",
    "Slugma",
    "Magcargo",
    "Swinub",
    "Piloswine",
    "Corsola",
    "Remoraid",
    "Octillery",
    "Delibird",
    "Mantine",
    "Skarmory",
    "Houndour",
    "Houndoom",
    "Kingdra",
    "Phanpy",
    "Donphan",
    "Porygon2",
    "Stantler",
    "Smeargle",
    "Tyrogue",
    "Hitmontop",
    "Smoochum",
    "Elekid",
    "Magby",
    "Miltank",
    "Blissey",
    "Raikou",
    "Entei",
    "Suicune",
    "Larvitar",
    "Pupitar",
    "Tyranitar",
    "Lugia",
    "Ho-Oh",
    "Celebi",
    "Treecko",
    "Grovyle",
    "Sceptile",
    "Torchic",
    "Combusken",
    "Blaziken",
    "Mudkip",
    "Marshtomp",
    "Swampert",
    "Poochyena",
    "Mightyena",
    "Zigzagoon",
    "Linoone",
    "Wurmple",
    "Silcoon",
    "Beautifly",
    "Cascoon",
    "Dustox",
    "Lotad",
    "Lombre",
    "Ludicolo",
    "Seedot",
    "Nuzleaf",
    "Shiftry",
    "Taillow",
    "Swellow",
    "Wingull",
    "Pelipper",
    "Ralts",
    "Kirlia",
    "Gardevoir",
    "Surskit",
    "Masquerain",
    "Shroomish",
    "Breloom",
    "Slakoth",
    "Vigoroth",
    "Slaking",
    "Nincada",
    "Ninjask",
    "Shedinja",
    "Whismur",
    "Loudred",
    "Exploud",
    "Makuhita",
    "Hariyama",
    "Azurill",
    "Nosepass",
    "Skitty",
    "Delcatty",
    "Sableye",
    "Mawile",
    "Aron",
    "Lairon",
    "Aggron",
    "Meditite",
    "Medicham",
    "Electrike",
    "Manectric",
    "Plusle",
    "Minun",
    "Volbeat",
    "Illumise",
    "Roselia",
    "Gulpin",
    "Swalot",
    "Carvanha",
    "Sharpedo",
    "Wailmer",
    "Wailord",
    "Numel",
    "Camerupt",
    "Torkoal",
    "Spoink",
    "Grumpig",
    "Spinda",
    "Trapinch",
    "Vibrava",
    "Flygon",
    "Cacnea",
    "Cacturne",
    "Swablu",
    "Altaria",
    "Zangoose",
    "Seviper",
    "Lunatone",
    "Solrock",
    "Barboach",
    "Whiscash",
    "Corphish",
    "Crawdaunt",
    "Baltoy",
    "Claydol",
    "Lileep",
    "Cradily",
    "Anorith",
    "Armaldo",
    "Feebas",
    "Milotic",
    "Castform",
    "Kecleon",
    "Shuppet",
    "Banette",
    "Duskull",
    "Dusclops",
    "Tropius",
    "Chimecho",
    "Absol",
    "Wynaut",
    "Snorunt",
    "Glalie",
    "Spheal",
    "Sealeo",
    "Walrein",
    "Clamperl",
    "Huntail",
    "Gorebyss",
    "Relicanth",
    "Luvdisc",
    "Bagon",
    "Shelgon",
    "Salamence",
    "Beldum",
    "Metang",
    "Metagross",
    "Regirock",
    "Regice",
    "Registeel",
    "Latias",
    "Latios",
    "Kyogre",
    "Groudon",
    "Rayquaza",
    "Jirachi",
    "Deoxys",
    "Turtwig",
    "Grotle",
    "Torterra",
    "Chimchar",
    "Monferno",
    "Infernape",
    "Piplup",
    "Prinplup",
    "Empoleon",
    "Starly",
    "Staravia",
    "Staraptor",
    "Bidoof",
    "Bibarel",
    "Kricketot",
    "Kricketune",
    "Shinx",
    "Luxio",
    "Luxray",
    "Budew",
    "Roserade",
    "Cranidos",
    "Rampardos",
    "Shieldon",
    "Bastiodon",
    "Burmy",
    "Wormadam",
    "Mothim",
    "Combee",
    "Vespiquen",
    "Pachirisu",
    "Buizel",
    "Floatzel",
    "Cherubi",
    "Cherrim",
    "Shellos",
    "Gastrodon",
    "Ambipom",
    "Drifloon",
    "Drifblim",
    "Buneary",
    "Lopunny",
    "Mismagius",
    "Honchkrow",
    "Glameow",
    "Purugly",
    "Chingling",
    "Stunky",
    "Skuntank",
    "Bronzor",
    "Bronzong",
    "Bonsly",
    "Mime Jr.",
    "Happiny",
    "Chatot",
    "Spiritomb",
    "Gible",
    "Gabite",
    "Garchomp",
    "Munchlax",
    "Riolu",
    "Lucario",
    "Hippopotas",
    "Hippowdon",
    "Skorupi",
    "Drapion",
    "Croagunk",
    "Toxicroak",
    "Carnivine",
    "Finneon",
    "Lumineon",
    "Mantyke",
    "Snover",
    "Abomasnow",
    "Weavile",
    "Magnezone",
    "Lickilicky",
    "Rhyperior",
    "Tangrowth",
    "Electivire",
    "Magmortar",
    "Togekiss",
    "Yanmega",
    "Leafeon",
    "Glaceon",
    "Gliscor",
    "Mamoswine",
    "Porygon-Z",
    "Gallade",
    "Probopass",
    "Dusknoir",
    "Froslass",
    "Rotom",
    "Uxie",
    "Mesprit",
    "Azelf",
    "Dialga",
    "Palkia",
    "Heatran",
    "Regigigas",
    "Giratina",
    "Cresselia",
    "Phione",
    "Manaphy",
    "Darkrai",
    "Shaymin",
    "Arceus",
    "Victini",
    "Snivy",
    "Servine",
    "Serperior",
    "Tepig",
    "Pignite",
    "Emboar",
    "Oshawott",
    "Dewott",
    "Samurott",
    "Patrat",
    "Watchog",
    "Lillipup",
    "Herdier",
    "Stoutland",
    "Purrloin",
    "Liepard",
    "Pansage",
    "Simisage",
    "Pansear",
    "Simisear",
    "Panpour",
    "Simipour",
    "Munna",
    "Musharna",
    "Pidove",
    "Tranquill",
    "Unfezant",
    "Blitzle",
    "Zebstrika",
    "Roggenrola",
    "Boldore",
    "Gigalith",
    "Woobat",
    "Swoobat",
    "Drilbur",
    "Excadrill",
    "Audino",
    "Timburr",
    "Gurdurr",
    "Conkeldurr",
    "Tympole",
    "Palpitoad",
    "Seismitoad",
    "Throh",
    "Sawk",
    "Sewaddle",
    "Swadloon",
    "Leavanny",
    "Venipede",
    "Whirlipede",
    "Scolipede",
    "Cottonee",
    "Whimsicott",
    "Petilil",
    "Lilligant",
    "Basculin",
    "Sandile",
    "Krokorok",
    "Krookodile",
    "Darumaka",
    "Darmanitan",
    "Maractus",
    "Dwebble",
    "Crustle",
    "Scraggy",
    "Scrafty",
    "Sigilyph",
    "Yamask",
    "Cofagrigus",
    "Tirtouga",
    "Carracosta",
    "Archen",
    "Archeops",
    "Trubbish",
    "Garbodor",
    "Zorua",
    "Zoroark",
    "Minccino",
    "Cinccino",
    "Gothita",
    "Gothorita",
    "Gothitelle",
    "Solosis",
    "Duosion",
    "Reuniclus",
    "Ducklett",
    "Swanna",
    "Vanillite",
    "Vanillish",
    "Vanilluxe",
    "Deerling",
    "Sawsbuck",
    "Emolga",
    "Karrablast",
    "Escavalier",
    "Foongus",
    "Amoonguss",
    "Frillish",
    "Jellicent",
    "Alomomola",
    "Joltik",
    "Galvantula",
    "Ferroseed",
    "Ferrothorn",
    "Klink",
    "Klang",
    "Klinklang",
    "Tynamo",
    "Eelektrik",
    "Eelektross",
    "Elgyem",
    "Beheeyem",
    "Litwick",
    "Lampent",
    "Chandelure",
    "Axew",
    "Fraxure",
    "Haxorus",
    "Cubchoo",
    "Beartic",
    "Cryogonal",
    "Shelmet",
    "Accelgor",
    "Stunfisk",
    "Mienfoo",
    "Mienshao",
    "Druddigon",
    "Golett",
    "Golurk",
    "Pawniard",
    "Bisharp",
    "Bouffalant",
    "Rufflet",
    "Braviary",
    "Vullaby",
    "Mandibuzz",
    "Heatmor",
    "Durant",
    "Deino",
    "Zweilous",
    "Hydreigon",
    "Larvesta",
    "Volcarona",
    "Cobalion",
    "Terrakion",
    "Virizion",
    "Tornadus",
    "Thundurus",
    "Reshiram",
    "Zekrom",
    "Landorus",
    "Kyurem",
    "Keldeo",
    "Meloetta",
    "Genesect",
    "Chespin",
    "Quilladin",
    "Chesnaught",
    "Fennekin",
    "Braixen",
    "Delphox",
    "Froakie",
    "Frogadier",
    "Greninja",
    "Bunnelby",
    "Diggersby",
    "Fletchling",
    "Fletchinder",
    "Talonflame",
    "Scatterbug",
    "Spewpa",
    "Vivillon",
    "Litleo",
    "Pyroar",
    "Flabébé",
    "Floette",
    "Florges",
    "Skiddo",
    "Gogoat",
    "Pancham",
    "Pangoro",
    "Furfrou",
    "Espurr",
    "Meowstic",
    "Honedge",
    "Doublade",
    "Aegislash",
    "Spritzee",
    "Aromatisse",
    "Swirlix",
    "Slurpuff",
    "Inkay",
    "Malamar",
    "Binacle",
    "Barbaracle",
    "Skrelp",
    "Dragalge",
    "Clauncher",
    "Clawitzer",
    "Helioptile",
    "Heliolisk",
    "Tyrunt",
    "Tyrantrum",
    "Amaura",
    "Aurorus",
    "Sylveon",
    "Hawlucha",
    "Dedenne",
    "Carbink",
    "Goomy",
    "Sliggoo",
    "Goodra",
    "Klefki",
    "Phantump",
    "Trevenant",
    "Pumpkaboo",
    "Gourgeist",
    "Bergmite",
    "Avalugg",
    "Noibat",
    "Noivern",
    "Xerneas",
    "Yveltal",
    "Zygarde",
    "Diancie",
    "Hoopa",
    "Volcanion",
    "Rowlet",
    "Dartrix",
    "Decidueye",
    "Litten",
    "Torracat",
    "Incineroar",
    "Popplio",
    "Brionne",
    "Primarina",
    "Pikipek",
    "Trumbeak",
    "Toucannon",
    "Yungoos",
    "Gumshoos",
    "Grubbin",
    "Charjabug",
    "Vikavolt",
    "Crabrawler",
    "Crabominable",
    "Oricorio",
    "Cutiefly",
    "Ribombee",
    "Rockruff",
    "Lycanroc",
    "Wishiwashi",
    "Mareanie",
    "Toxapex",
    "Mudbray",
    "Mudsdale",
    "Dewpider",
    "Araquanid",
    "Fomantis",
    "Lurantis",
    "Morelull",
    "Shiinotic",
    "Salandit",
    "Salazzle",
    "Stufful",
    "Bewear",
    "Bounsweet",
    "Steenee",
    "Tsareena",
    "Comfey",
    "Oranguru",
    "Passimian",
    "Wimpod",
    "Golisopod",
    "Sandygast",
    "Palossand",
    "Pyukumuku",
    "Type: Null",
    "Silvally",
    "Minior",
    "Komala",
    "Turtonator",
    "Togedemaru",
    "Mimikyu",
    "Bruxish",
    "Drampa",
    "Dhelmise",
    "Jangmo-o",
    "Hakamo-o",
    "Kommo-o",
    "Tapu Koko",
    "Tapu Lele",
    "Tapu Bulu",
    "Tapu Fini",
    "Cosmog",
    "Cosmoem",
    "Solgaleo",
    "Lunala",
    "Nihilego",
    "Buzzwole",
    "Pheromosa",
    "Xurkitree",
    "Celesteela",
    "Kartana",
    "Guzzlord",
    "Necrozma",
    "Magearna",
    "Marshadow",
    "Poipole",
    "Naganadel",
    "Stakataka",
    "Blacephalon",
    "Zeraora"
};

enum regions
{
    KANTO,
    JOHTO,
    HOENN,
    SINNOH,
    UNOVA,
    KALOS,
    ALOLA
};

enum pokemonTypes
{
    NORMAL,
    FIRE,
    WATER,
    ELECTRIC,
    GRASS,
    ICE,
    FIGHTING,
    POISON,
    GROUND,
    FLYING,
    PSYCHIC,
    BUG,
    ROCK,
    GHOST,
    DRAGON,
    DARK,
    STEEL,
    FAIRY,
    VARIABLE_FORM,
    NONE
};

struct typings
{
    pokemonTypes type;
    pokemonTypes subType;
};

std::vector<typings> pokemonTypingVec
{
    /*KANTO*/
    {GRASS, POISON},
    {GRASS, POISON},
    {GRASS, POISON},
    {FIRE, NONE},
    {FIRE, NONE},
    {FIRE, FLYING},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {BUG, NONE},
    {BUG, NONE},
    {BUG, FLYING},
    {BUG, POISON},
    {BUG, POISON},
    {BUG, POISON},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {POISON, NONE},
    {POISON, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {GROUND, NONE},
    {GROUND, NONE},
    {POISON, NONE},
    {POISON, NONE},
    {POISON, GROUND},
    {POISON, NONE},
    {POISON, NONE},
    {POISON, GROUND},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {FIRE, NONE},
    {FIRE, NONE},
    {NORMAL, FAIRY},
    {NORMAL, FAIRY},
    {POISON, FLYING},
    {POISON, FLYING},
    {GRASS, POISON},
    {GRASS, POISON},
    {GRASS, POISON},
    {BUG, GRASS},
    {BUG, GRASS},
    {BUG, POISON},
    {BUG, POISON},
    {GROUND, NONE},
    {GROUND, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {FIRE, NONE},
    {FIRE, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, FIGHTING},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {GRASS, POISON},
    {GRASS, POISON},
    {GRASS, POISON},
    {WATER, POISON},
    {WATER, POISON},
    {ROCK, GROUND},
    {ROCK, GROUND},
    {ROCK, GROUND},
    {FIRE, NONE},
    {FIRE, NONE},
    {WATER, PSYCHIC},
    {WATER, PSYCHIC},
    {ELECTRIC, STEEL},
    {ELECTRIC, STEEL},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {WATER, NONE},
    {WATER, ICE},
    {POISON, NONE},
    {POISON, NONE},
    {WATER, NONE},
    {WATER, ICE},
    {GHOST, POISON},
    {GHOST, POISON},
    {GHOST, POISON},
    {ROCK, GROUND},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {GRASS, PSYCHIC},
    {GRASS, PSYCHIC},
    {GROUND, NONE},
    {GROUND, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {NORMAL, NONE},
    {POISON, NONE},
    {POISON, NONE},
    {GROUND, ROCK},
    {GROUND, ROCK},
    {NORMAL, NONE},
    {GRASS, NONE},
    {NORMAL, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, PSYCHIC},
    {PSYCHIC, FAIRY},
    {BUG, FLYING},
    {ICE, PSYCHIC},
    {ELECTRIC, NONE},
    {FIRE, NONE},
    {BUG, NONE},
    {NORMAL, NONE},
    {WATER, NONE},
    {WATER, FLYING},
    {WATER, ICE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {WATER, NONE},
    {ELECTRIC, NONE},
    {FIRE, NONE},
    {NORMAL, NONE},
    {ROCK, WATER},
    {ROCK, WATER},
    {ROCK, WATER},
    {ROCK, WATER},
    {ROCK, FLYING},
    {NORMAL, NONE},
    {ICE, FLYING},
    {ELECTRIC, FLYING},
    {FIRE, FLYING},
    {DRAGON, NONE},
    {DRAGON, NONE},
    {DRAGON, FLYING},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},

    /*JOHTO*/
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {FIRE, NONE},
    {FIRE, NONE},
    {FIRE, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {BUG, FLYING},
    {BUG, FLYING},
    {BUG, POISON},
    {BUG, POISON},
    {POISON, FLYING},
    {WATER, ELECTRIC},
    {WATER, ELECTRIC},
    {ELECTRIC, NONE},
    {FAIRY, NONE},
    {NORMAL, FAIRY},
    {FAIRY, NONE},
    {FAIRY, FLYING},
    {PSYCHIC, FLYING},
    {PSYCHIC, FLYING},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {GRASS, NONE},
    {WATER, FAIRY},
    {WATER, FAIRY},
    {ROCK, NONE},
    {WATER, NONE},
    {GRASS, FLYING},
    {GRASS, FLYING},
    {GRASS, FLYING},
    {NORMAL, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {BUG, FLYING},
    {WATER, GROUND},
    {WATER, GROUND},
    {PSYCHIC, NONE},
    {DARK, NONE},
    {DARK, FLYING},
    {WATER, PSYCHIC},
    {GHOST, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {NORMAL, PSYCHIC},
    {BUG, NONE},
    {BUG, STEEL},
    {NORMAL, NONE},
    {GROUND, FLYING},
    {STEEL, GROUND},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {WATER, POISON},
    {BUG, STEEL},
    {BUG, ROCK},
    {BUG, FIGHTING},
    {DARK, ICE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {FIRE, NONE},
    {FIRE, ROCK},
    {ICE, GROUND},
    {ICE, GROUND},
    {WATER, ROCK},
    {WATER, NONE},
    {WATER, NONE},
    {ICE, FLYING},
    {WATER, FLYING},
    {STEEL, FLYING},
    {DARK, FIRE},
    {DARK, FIRE},
    {WATER, DRAGON},
    {GROUND, NONE},
    {GROUND, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {ICE, PSYCHIC},
    {ELECTRIC, NONE},
    {FIRE, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {ELECTRIC, NONE},
    {FIRE, NONE},
    {WATER, NONE},
    {ROCK, GROUND},
    {ROCK, GROUND},
    {ROCK, DARK},
    {PSYCHIC, FLYING},
    {FIRE, FLYING},
    {PSYCHIC, GRASS},

    /*HOENN*/
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {FIRE, NONE},
    {FIRE, FIGHTING},
    {FIRE, FIGHTING},
    {WATER, NONE},
    {WATER, GROUND},
    {WATER, GROUND},
    {DARK, NONE},
    {DARK, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {BUG, NONE},
    {BUG, NONE},
    {BUG, FLYING},
    {BUG, NONE},
    {BUG, POISON},
    {WATER, GRASS},
    {WATER, GRASS},
    {WATER, GRASS},
    {GRASS, NONE},
    {GRASS, DARK},
    {GRASS, DARK},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {WATER, FLYING},
    {WATER, FLYING},
    {PSYCHIC, FAIRY},
    {PSYCHIC, FAIRY},
    {PSYCHIC, FAIRY},
    {BUG, WATER},
    {BUG, FLYING},
    {GRASS, NONE},
    {GRASS, FIGHTING},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {BUG, GROUND},
    {BUG, FLYING},
    {BUG, GHOST},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {NORMAL, FAIRY},
    {ROCK, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {DARK, GHOST},
    {STEEL, FAIRY},
    {STEEL, ROCK},
    {STEEL, ROCK},
    {STEEL, ROCK},
    {FIGHTING, PSYCHIC},
    {FIGHTING, PSYCHIC},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {BUG, NONE},
    {BUG, NONE},
    {GRASS, POISON},
    {POISON, NONE},
    {POISON, NONE},
    {WATER, DARK},
    {WATER, DARK},
    {WATER, NONE},
    {WATER, NONE},
    {FIRE, GROUND},
    {FIRE, GROUND},
    {FIRE, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {NORMAL, NONE},
    {GROUND, NONE},
    {GROUND, DRAGON},
    {GROUND, DRAGON},
    {GRASS, NONE},
    {GRASS, DARK},
    {NORMAL, FLYING},
    {DRAGON, FLYING},
    {NORMAL, NONE},
    {POISON, NONE},
    {ROCK, PSYCHIC},
    {ROCK, PSYCHIC},
    {WATER, GROUND},
    {WATER, GROUND},
    {WATER, NONE},
    {WATER, DARK},
    {GROUND, PSYCHIC},
    {GROUND, PSYCHIC},
    {ROCK, GRASS},
    {ROCK, GRASS},
    {ROCK, BUG},
    {ROCK, BUG},
    {WATER, NONE},
    {WATER, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {GHOST, NONE},
    {GHOST, NONE},
    {GHOST, NONE},
    {GHOST, NONE},
    {GRASS, FLYING},
    {PSYCHIC, NONE},
    {DARK, NONE},
    {PSYCHIC, NONE},
    {ICE, NONE},
    {ICE, NONE},
    {ICE, WATER},
    {ICE, WATER},
    {ICE, WATER},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, ROCK},
    {WATER, NONE},
    {DRAGON, NONE},
    {DRAGON, NONE},
    {DRAGON, FLYING},
    {STEEL, PSYCHIC},
    {STEEL, PSYCHIC},
    {STEEL, PSYCHIC},
    {ROCK, NONE},
    {ICE, NONE},
    {STEEL, NONE},
    {DRAGON, PSYCHIC},
    {DRAGON, PSYCHIC},
    {WATER, NONE},
    {GROUND, NONE},
    {DRAGON, FLYING},
    {STEEL, PSYCHIC},
    {PSYCHIC, NONE},

    /*SINNOH*/
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, GROUND},
    {FIRE, NONE},
    {FIRE, FIGHTING},
    {FIRE, FIGHTING},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, STEEL},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, NONE},
    {NORMAL, WATER},
    {BUG, NONE},
    {BUG, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {GRASS, POISON},
    {GRASS, POISON},
    {ROCK, NONE},
    {ROCK, NONE},
    {ROCK, STEEL},
    {ROCK, STEEL},
    {BUG, NONE},
    {BUG, VARIABLE_FORM},
    {BUG, FLYING},
    {BUG, FLYING},
    {BUG, FLYING},
    {ELECTRIC, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {WATER, NONE},
    {WATER, GROUND},
    {NORMAL, NONE},
    {GHOST, FLYING},
    {GHOST, FLYING},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {GHOST, NONE},
    {DARK, FLYING},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {PSYCHIC, NONE},
    {POISON, DARK},
    {POISON, DARK},
    {STEEL, PSYCHIC},
    {STEEL, PSYCHIC},
    {ROCK, NONE},
    {PSYCHIC, FAIRY},
    {NORMAL, NONE},
    {NORMAL, FLYING},
    {GHOST, DARK},
    {DRAGON, GROUND},
    {DRAGON, GROUND},
    {DRAGON, GROUND},
    {NORMAL, NONE},
    {FIGHTING, NONE},
    {FIGHTING, STEEL},
    {GROUND, NONE},
    {GROUND, NONE},
    {POISON, BUG},
    {POISON, DARK},
    {POISON, FIGHTING},
    {POISON, FIGHTING},
    {GRASS, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, FLYING},
    {GRASS, ICE},
    {GRASS, ICE},
    {DARK, ICE},
    {ELECTRIC, STEEL},
    {NORMAL, NONE},
    {GROUND, ROCK},
    {GRASS, NONE},
    {ELECTRIC, NONE},
    {FIRE, NONE},
    {FAIRY, FLYING},
    {BUG, FLYING},
    {GRASS, NONE},
    {ICE, NONE},
    {GROUND, FLYING},
    {ICE, GROUND},
    {NORMAL, NONE},
    {PSYCHIC, FIGHTING},
    {ROCK, STEEL},
    {GHOST, NONE},
    {ICE, GHOST},
    {ELECTRIC, VARIABLE_FORM},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {STEEL, DRAGON},
    {WATER, DRAGON},
    {FIRE, STEEL},
    {NORMAL, NONE},
    {GHOST, DRAGON},
    {PSYCHIC, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {DARK, NONE},
    {GRASS, VARIABLE_FORM},
    {NORMAL, NONE},

    /*UNOVA*/
    {PSYCHIC, FIRE},
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {FIRE, NONE},
    {FIRE, FIGHTING},
    {FIRE, FIGHTING},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {DARK, NONE},
    {DARK, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {FIRE, NONE},
    {FIRE, NONE},
    {WATER, NONE},
    {WATER, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {ROCK, NONE},
    {ROCK, NONE},
    {ROCK, NONE},
    {PSYCHIC, FLYING},
    {PSYCHIC, FLYING},
    {GROUND, NONE},
    {GROUND, STEEL},
    {NORMAL, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {WATER, NONE},
    {WATER, GROUND},
    {WATER, GROUND},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {BUG, GRASS},
    {BUG, GRASS},
    {BUG, GRASS},
    {BUG, POISON},
    {BUG, POISON},
    {BUG, POISON},
    {GRASS, FAIRY},
    {GRASS, FAIRY},
    {GRASS, NONE},
    {GRASS, NONE},
    {WATER, NONE},
    {GROUND, DARK},
    {GROUND, DARK},
    {GROUND, DARK},
    {FIRE, NONE},
    {FIRE, VARIABLE_FORM},
    {GRASS, NONE},
    {BUG, ROCK},
    {BUG, ROCK},
    {DARK, FIGHTING},
    {DARK, FIGHTING},
    {PSYCHIC, FLYING},
    {GHOST, NONE},
    {GHOST, NONE},
    {WATER, ROCK},
    {WATER, ROCK},
    {ROCK, FLYING},
    {ROCK, FLYING},
    {POISON, NONE},
    {POISON, NONE},
    {DARK, NONE},
    {DARK, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {WATER, FLYING},
    {WATER, FLYING},
    {ICE, NONE},
    {ICE, NONE},
    {ICE, NONE},
    {NORMAL, GRASS},
    {NORMAL, GRASS},
    {ELECTRIC, FLYING},
    {BUG, NONE},
    {BUG, STEEL},
    {GRASS, POISON},
    {GRASS, POISON},
    {WATER, GHOST},
    {WATER, GHOST},
    {WATER, NONE},
    {BUG, ELECTRIC},
    {BUG, ELECTRIC},
    {GRASS, STEEL},
    {GRASS, STEEL},
    {STEEL, NONE},
    {STEEL, NONE},
    {STEEL, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {ELECTRIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {GHOST, FIRE},
    {GHOST, FIRE},
    {GHOST, FIRE},
    {DRAGON, NONE},
    {DRAGON, NONE},
    {DRAGON, NONE},
    {ICE, NONE},
    {ICE, NONE},
    {ICE, NONE},
    {BUG, NONE},
    {BUG, NONE},
    {GROUND, ELECTRIC},
    {FIGHTING, NONE},
    {FIGHTING, NONE},
    {DRAGON, NONE},
    {GROUND, GHOST},
    {GROUND, GHOST},
    {DARK, STEEL},
    {DARK, STEEL},
    {NORMAL, NONE},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {DARK, FLYING},
    {DARK, FLYING},
    {FIRE, NONE},
    {BUG, STEEL},
    {DARK, DRAGON},
    {DARK, DRAGON},
    {DARK, DRAGON},
    {BUG, FIRE},
    {BUG, FIRE},
    {STEEL, FIGHTING},
    {ROCK, FIGHTING},
    {GRASS, FIGHTING},
    {FLYING, NONE},
    {ELECTRIC, FLYING},
    {DRAGON, FIRE},
    {DRAGON, ELECTRIC},
    {GROUND, FLYING},
    {DRAGON, ICE},
    {WATER, FIGHTING},
    {NORMAL, VARIABLE_FORM},
    {BUG, STEEL},

    /*KALOS*/
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, FIGHTING},
    {FIRE, NONE},
    {FIRE, NONE},
    {FIRE, PSYCHIC},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, DARK},
    {NORMAL, NONE},
    {NORMAL, GROUND},
    {NORMAL, FLYING},
    {FIRE, FLYING},
    {FIRE, FLYING},
    {BUG, NONE},
    {BUG, NONE},
    {BUG, FLYING},
    {FIRE, NORMAL},
    {FIRE, NORMAL},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {FIGHTING, NONE},
    {FIGHTING, DARK},
    {NORMAL, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {STEEL, GHOST},
    {STEEL, GHOST},
    {STEEL, GHOST},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {FAIRY, NONE},
    {DARK, PSYCHIC},
    {DARK, PSYCHIC},
    {ROCK, WATER},
    {ROCK, WATER},
    {POISON, WATER},
    {POISON, DRAGON},
    {WATER, NONE},
    {WATER, NONE},
    {ELECTRIC, NORMAL},
    {ELECTRIC, NORMAL},
    {ROCK, DRAGON},
    {ROCK, DRAGON},
    {ROCK, ICE},
    {ROCK, ICE},
    {FAIRY, NONE},
    {FIGHTING, FLYING},
    {ELECTRIC, FAIRY},
    {ROCK, FAIRY},
    {DRAGON, NONE},
    {DRAGON, NONE},
    {DRAGON, NONE},
    {STEEL, FAIRY},
    {GHOST, GRASS},
    {GHOST, GRASS},
    {GHOST, GRASS},
    {GHOST, GRASS},
    {ICE, NONE},
    {ICE, NONE},
    {FLYING, DRAGON},
    {FLYING, DRAGON},
    {FAIRY, NONE},
    {DARK, FLYING},
    {DRAGON, GROUND},
    {ROCK, FAIRY},
    {PSYCHIC, VARIABLE_FORM},
    {FIRE, WATER},

    /*ALOLA*/
    {GRASS, FLYING},
    {GRASS, FLYING},
    {GRASS, GHOST},
    {FIRE, NONE},
    {FIRE, NONE},
    {FIRE, DARK},
    {WATER, NONE},
    {WATER, NONE},
    {WATER, FAIRY},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, FLYING},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {BUG, NONE},
    {BUG, ELECTRIC},
    {BUG, ELECTRIC},
    {FIGHTING, NONE},
    {FIGHTING, ICE},
    {VARIABLE_FORM, FLYING},
    {BUG, FAIRY},
    {BUG, FAIRY},
    {ROCK, NONE},
    {ROCK, NONE},
    {WATER, NONE},
    {POISON, WATER},
    {POISON, WATER},
    {GROUND, NONE},
    {GROUND, NONE},
    {WATER, BUG},
    {WATER, BUG},
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, FAIRY},
    {GRASS, FAIRY},
    {POISON, FIRE},
    {POISON, FIRE},
    {NORMAL, FIGHTING},
    {NORMAL, FIGHTING},
    {GRASS, NONE},
    {GRASS, NONE},
    {GRASS, NONE},
    {FAIRY, NONE},
    {NORMAL, PSYCHIC},
    {FIGHTING, NONE},
    {BUG, WATER},
    {BUG, WATER},
    {GHOST, GROUND},
    {GHOST, GROUND},
    {WATER, NONE},
    {NORMAL, NONE},
    {NORMAL, NONE},
    {ROCK, FLYING},
    {NORMAL, NONE},
    {FIRE, DRAGON},
    {ELECTRIC, STEEL},
    {GHOST, FAIRY},
    {WATER, PSYCHIC},
    {NORMAL, DRAGON},
    {GHOST, GRASS},
    {DRAGON, NONE},
    {DRAGON, FIGHTING},
    {DRAGON, FIGHTING},
    {ELECTRIC, FAIRY},
    {PSYCHIC, FAIRY},
    {GRASS, FAIRY},
    {WATER, FAIRY},
    {PSYCHIC, NONE},
    {PSYCHIC, NONE},
    {PSYCHIC, STEEL},
    {PSYCHIC, GHOST},
    {ROCK, POISON},
    {BUG, FIGHTING},
    {BUG, FIGHTING},
    {ELECTRIC, NONE},
    {STEEL, FLYING},
    {GRASS, STEEL},
    {DARK, DRAGON},
    {PSYCHIC, NONE},
    {STEEL, FAIRY},
    {FIGHTING, GHOST},
    {POISON, NONE},
    {POISON, DRAGON},
    {ROCK, STEEL},
    {FIRE, GHOST},
    {ELECTRIC, NONE}
};

enum evolutionStages
{
    UNEVOLVED,
    FIRST,
    SECOND
};

std::vector<evolutionStages> evolutionStageVec
{
    /*KANTO*/
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    FIRST,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,

    /*JOHTO*/
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    SECOND,
    FIRST,
    SECOND,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    FIRST,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,

    /*HOENN*/
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,

    /*SINNOH*/
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    FIRST,
    SECOND,
    FIRST,
    SECOND,
    FIRST,
    SECOND,
    SECOND,
    SECOND,
    FIRST,
    FIRST,
    FIRST,
    FIRST,
    SECOND,
    SECOND,
    SECOND,
    FIRST,
    SECOND,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,

    /*UNOVA*/
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,

    /*KALOS*/
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,

    /*ALOLA*/
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    SECOND,
    SECOND,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED,
    FIRST,
    UNEVOLVED,
    UNEVOLVED,
    UNEVOLVED 
};

std::vector<unsigned short> legendaryIndicesVec
{
    143,
    144,
    145,
    149,
    150,
    242,
    243,
    244,
    248,
    249,
    250,
    376,
    377,
    378,
    379,
    380,
    381,
    382,
    383,
    384,
    385,
    479,
    480,
    481,
    482,
    483,
    484,
    485,
    486,
    487,
    488,
    489,
    490,
    491,
    492,
    493,
    637,
    638,
    639,
    640,
    641,
    642,
    643,
    644,
    645,
    646,
    647,
    648,
    715,
    716,
    717,
    718,
    719,
    720,
    771,
    772,
    784,
    785,
    786,
    787,
    788,
    789,
    790,
    791,
    799,
    800,
    801,
    806
};

std::vector<unsigned short> mythicalIndicesVec
{
    150,
    250,
    384,
    385,
    488,
    489,
    490,
    491,
    492,
    493,
    646,
    647,
    648,
    718,
    719,
    720,
    800,
    801,
    806
};

std::vector<unsigned short> starterIndicesVec
{
    0, 1, 2, 3, 4, 5, 6, 7, 8,
    151, 152, 153, 154, 155, 156, 157, 158, 159,
    251, 252, 253, 254, 255, 256, 257, 258, 259,
    386, 387, 388, 389, 390, 391, 392, 393, 394,
    494, 495, 496, 497, 498, 499, 500, 501, 502,
    649, 650, 651, 652, 653, 654, 655, 656, 657,
    721, 722, 723, 724, 725, 726, 727, 728, 729
};

std::vector<unsigned short> genderlessIndicesVec
{
    80,
    81,
    99,
    100,
    119,
    120,
    131,
    136,
    143,
    144,
    145,
    149,
    150,
    200,
    232,
    242,
    243,
    244,
    248,
    249,
    250,
    291,
    336,
    227,
    342,
    343,
    373,
    374,
    375,
    376,
    377,
    378,
    381,
    382,
    383,
    384,
    385,
    435,
    436,
    461,
    473,
    478,
    479,
    480,
    481,
    482,
    483,
    485,
    486,
    488,
    489,
    490,
    491,
    492,
    493,
    598,
    599,
    600,
    614,
    621,
    622,
    637,
    638,
    639,
    642,
    643,
    645,
    646,
    647,
    648,
    702,
    715,
    716,
    717,
    718,
    719,
    720,
    771,
    772,
    773,
    784,
    785,
    786,
    787,
    788,
    789,
    790,
    791,
    792,
    793,
    794,
    795,
    796,
    797,
    798,
    799,
    800,
    801,
    802,
    803,
    804,
    805,
    806
};

enum evolutionTypes
{
    LEVEL,
    LEVEL_MOVE,
    ITEM,
    TRADE,
    TRADE_ITEM,
    FRIENDSHIP,
    SPECIAL
};

std::map<unsigned short, evolutionTypes> canEvolveByMap
{
    /*KANTO*/
    {0, LEVEL},
    {1, LEVEL},
    {3, LEVEL},
    {4, LEVEL},
    {6, LEVEL},
    {7, LEVEL},
    {9, LEVEL},
    {10, LEVEL},
    {12, LEVEL},
    {13, LEVEL},
    {15, LEVEL},
    {16, LEVEL},
    {18, LEVEL},
    {20, LEVEL},
    {22, LEVEL},
    {24, ITEM},
    {26, LEVEL},
    {28, LEVEL},
    {29, ITEM},
    {31, LEVEL},
    {32, ITEM},
    {34, ITEM},
    {36, ITEM},
    {38, ITEM},
    {40, LEVEL},
    {41, FRIENDSHIP},
    {42, LEVEL},
    {43, ITEM},
    {45, LEVEL},
    {47, LEVEL},
    {49, LEVEL},
    {51, LEVEL},
    {53, LEVEL},
    {55, LEVEL},
    {57, ITEM},
    {59, LEVEL},
    {60, SPECIAL},
    {62, LEVEL},
    {63, TRADE},
    {65, LEVEL},
    {66, TRADE},
    {68, LEVEL},
    {69, ITEM},
    {71, LEVEL},
    {73, LEVEL},
    {74, TRADE},
    {76, LEVEL},
    {78, SPECIAL},
    {80, LEVEL},
    {81, SPECIAL},
    {83, LEVEL},
    {85, LEVEL},
    {87, LEVEL},
    {89, ITEM},
    {91, LEVEL},
    {92, TRADE},
    {94, TRADE_ITEM},
    {95, LEVEL},
    {97, LEVEL},
    {99, LEVEL},
    {101, ITEM},
    {103, LEVEL},
    {107, LEVEL_MOVE},
    {108, LEVEL},
    {110, LEVEL},
    {111, TRADE_ITEM},
    {112, FRIENDSHIP},
    {113, LEVEL_MOVE},
    {115, LEVEL},
    {116, TRADE_ITEM},
    {117, LEVEL},
    {119, LEVEL},
    {122, TRADE_ITEM},
    {124, TRADE_ITEM},
    {125, TRADE_ITEM},
    {128, LEVEL},
    {132, SPECIAL},
    {136, TRADE_ITEM},
    {137, LEVEL},
    {139, LEVEL},
    {146, LEVEL},
    {147, LEVEL},

    /*JOHTO*/
    {151, LEVEL},
    {152, LEVEL},
    {154, LEVEL},
    {155, LEVEL},
    {157, LEVEL},
    {158, LEVEL},
    {160, LEVEL},
    {162, LEVEL},
    {164, LEVEL},
    {166, LEVEL},
    {169, LEVEL},
    {171, FRIENDSHIP},
    {172, FRIENDSHIP},
    {173, FRIENDSHIP},
    {174, FRIENDSHIP},
    {175, ITEM},
    {176, LEVEL},
    {178, LEVEL},
    {179, LEVEL},
    {182, LEVEL},
    {186, LEVEL},
    {187, LEVEL},
    {189, LEVEL_MOVE},
    {190, ITEM},
    {192, LEVEL_MOVE},
    {193, LEVEL},
    {197, ITEM},
    {199, ITEM},
    {203, LEVEL},
    {206, SPECIAL},
    {208, LEVEL},
    {214, SPECIAL},
    {215, LEVEL},
    {217, LEVEL},
    {219, LEVEL},
    {220, LEVEL_MOVE},
    {222, LEVEL},
    {227, LEVEL},
    {230, LEVEL},
    {232, TRADE_ITEM},
    {235, SPECIAL},
    {237, LEVEL},
    {238, LEVEL},
    {239, LEVEL},
    {245, LEVEL},
    {246, LEVEL},

    /*HOENN*/
    {251, LEVEL},
    {252, LEVEL},
    {254, LEVEL},
    {255, LEVEL},
    {257, LEVEL},
    {258, LEVEL},
    {260, LEVEL},
    {262, LEVEL},
    {264, LEVEL},
    {265, LEVEL},
    {267, LEVEL},
    {270, LEVEL},
    {271, LEVEL},
    {272, LEVEL},
    {273, LEVEL},
    {275, LEVEL},
    {278, LEVEL},
    {279, LEVEL},
    {280, SPECIAL},
    {282, LEVEL},
    {284, LEVEL},
    {286, LEVEL},
    {287, LEVEL},
    {289, LEVEL},
    {292, LEVEL},
    {293, LEVEL},
    {295, LEVEL},
    {297, FRIENDSHIP},
    {298, SPECIAL},
    {299, LEVEL},
    {303, LEVEL},
    {304, LEVEL},
    {306, LEVEL},
    {308, LEVEL},
    {314, ITEM},
    {315, LEVEL},
    {317, LEVEL},
    {319, LEVEL},
    {321, LEVEL},
    {324, LEVEL},
    {327, LEVEL},
    {328, LEVEL},
    {330, LEVEL},
    {332, LEVEL},
    {338, LEVEL},
    {340, LEVEL},
    {342, LEVEL},
    {344, LEVEL},
    {346, LEVEL},
    {348, TRADE_ITEM},
    {352, LEVEL},
    {354, LEVEL},
    {355, TRADE_ITEM},
    {359, LEVEL},
    {360, SPECIAL},
    {362, LEVEL},
    {363, LEVEL},
    {365, TRADE_ITEM},
    {370, LEVEL},
    {371, LEVEL},
    {373, LEVEL},
    {374, LEVEL},

    /*SINNOH*/
    {386, LEVEL},
    {387, LEVEL},
    {389, LEVEL},
    {390, LEVEL},
    {392, LEVEL},
    {393, LEVEL},
    {395, LEVEL},
    {396, LEVEL},
    {398, LEVEL},
    {400, LEVEL},
    {402, LEVEL},
    {403, LEVEL},
    {405, SPECIAL},
    {407, LEVEL},
    {409, LEVEL},
    {411, SPECIAL},
    {414, SPECIAL},
    {417, LEVEL},
    {419, LEVEL},
    {421, LEVEL},
    {424, LEVEL},
    {426, LEVEL},
    {430, LEVEL},
    {432, SPECIAL},
    {433, LEVEL},
    {435, LEVEL},
    {437, LEVEL_MOVE},
    {438, LEVEL_MOVE},
    {439, SPECIAL},
    {442, LEVEL},
    {443, LEVEL},
    {445, FRIENDSHIP},
    {446, SPECIAL},
    {448, LEVEL},
    {450, LEVEL},
    {452, LEVEL},
    {455, LEVEL},
    {457, SPECIAL},
    {458, LEVEL},

    /*UNOVA*/
    {494, LEVEL},
    {495, LEVEL},
    {497, LEVEL},
    {498, LEVEL},
    {500, LEVEL},
    {501, LEVEL},
    {503, LEVEL},
    {505, LEVEL},
    {506, LEVEL},
    {508, LEVEL},
    {510, LEVEL},
    {512, LEVEL},
    {514, LEVEL},
    {516, LEVEL},
    {518, LEVEL},
    {519, LEVEL},
    {521, LEVEL},
    {523, LEVEL},
    {524, TRADE},
    {526, FRIENDSHIP},
    {528, LEVEL},
    {531, LEVEL},
    {532, TRADE},
    {534, LEVEL},
    {535, LEVEL},
    {539, LEVEL},
    {540, FRIENDSHIP},
    {542, LEVEL},
    {543, LEVEL},
    {545, ITEM},
    {547, ITEM},
    {550, LEVEL},
    {551, LEVEL},
    {553, LEVEL},
    {556, LEVEL},
    {558, LEVEL},
    {561, LEVEL},
    {563, LEVEL},
    {565, LEVEL},
    {567, LEVEL},
    {569, LEVEL},
    {571, ITEM},
    {573, LEVEL},
    {574, LEVEL},
    {576, LEVEL},
    {577, LEVEL},
    {579, LEVEL},
    {581, LEVEL},
    {582, LEVEL},
    {584, LEVEL},
    {587, SPECIAL},
    {589, LEVEL},
    {591, LEVEL},
    {594, LEVEL},
    {596, LEVEL},
    {598, LEVEL},
    {599, LEVEL},
    {601, LEVEL},
    {602, ITEM},
    {604, LEVEL},
    {606, LEVEL},
    {607, ITEM},
    {609, LEVEL},
    {610, LEVEL},
    {612, LEVEL},
    {615, SPECIAL},
    {618, LEVEL},
    {621, LEVEL},
    {623, LEVEL},
    {626, LEVEL},
    {628, LEVEL},
    {632, LEVEL},
    {633, LEVEL},
    {635, LEVEL},

    /*KALOS*/
    {649, LEVEL},
    {650, LEVEL},
    {652, LEVEL},
    {653, LEVEL},
    {655, LEVEL},
    {656, LEVEL},
    {658, LEVEL},
    {660, LEVEL},
    {661, LEVEL},
    {663, LEVEL},
    {664, LEVEL},
    {666, LEVEL},
    {668, LEVEL},
    {669, ITEM},
    {671, LEVEL},
    {673, LEVEL},
    {676, LEVEL},
    {678, LEVEL},
    {679, ITEM},
    {681, TRADE_ITEM},
    {683, TRADE_ITEM},
    {685, SPECIAL},
    {687, LEVEL},
    {689, LEVEL},
    {691, LEVEL},
    {693, ITEM},
    {695, SPECIAL},
    {697, SPECIAL},
    {703, LEVEL},
    {704, SPECIAL},
    {707, TRADE},
    {709, TRADE},
    {711, LEVEL},
    {713, LEVEL},

    /*ALOLA*/
    {721, LEVEL},
    {722, LEVEL},
    {724, LEVEL},
    {725, LEVEL},
    {727, LEVEL},
    {728, LEVEL},
    {730, LEVEL},
    {731, LEVEL},
    {733, LEVEL},
    {735, LEVEL},
    {736, SPECIAL},
    {738, SPECIAL},
    {741, LEVEL},
    {743, SPECIAL},
    {746, LEVEL},
    {748, LEVEL},
    {750, LEVEL},
    {752, SPECIAL},
    {754, LEVEL},
    {756, SPECIAL},
    {758, LEVEL},
    {760, LEVEL},
    {761, LEVEL_MOVE},
    {766, LEVEL},
    {768, LEVEL},
    {771, FRIENDSHIP},
    {781, LEVEL},
    {782, LEVEL},
    {788, LEVEL},
    {789, LEVEL},
    {802, LEVEL_MOVE}
};

enum gender
{
    MALE,
    FEMALE
};

std::map<unsigned short, gender> monoGenderMap
{
    {28, FEMALE},
    {29, FEMALE},
    {30, FEMALE},
    {31, MALE},
    {32, MALE},
    {33, MALE},
    {105, MALE},
    {106, MALE},
    {112, FEMALE},
    {114, FEMALE},
    {123, FEMALE},
    {127, MALE},
    {235, MALE},
    {236, MALE},
    {237, FEMALE},
    {240, FEMALE},
    {241, FEMALE},
    {312, MALE},
    {313, FEMALE},
    {379, FEMALE},
    {380, MALE},
    {439, FEMALE},
    {475, MALE},
    {477, FEMALE},
    {412, FEMALE},
    {413, MALE},
    {415, FEMALE},
    {487, FEMALE},
    {537, MALE},
    {538, MALE},
    {547, FEMALE},
    {548, FEMALE},
    {626, MALE},
    {627, MALE},
    {628, FEMALE},
    {629, FEMALE},
    {640, MALE},
    {641, MALE},
    {644, MALE},
    {668, FEMALE},
    {669, FEMALE},
    {670, FEMALE},
    {757, FEMALE},
    {760, FEMALE},
    {761, FEMALE},
    {762, FEMALE}
};

std::vector<std::string> pokedexCategoryVec
{
    /*KANTO*/
    "Seed",
    "Seed",
    "Seed",
    "Lizard",
    "Flame",
    "Flame",
    "Tiny Turtle",
    "Turtle",
    "Shellfish",
    "Worm",
    "Cocoon",
    "Butterfly",
    "Hairy Bug",
    "Cocoon",
    "Poison Bee",
    "Tiny Bird",
    "Bird",
    "Bird",
    "Mouse",
    "Mouse",
    "Tiny Bird",
    "Beak",
    "Snake",
    "Cobra",
    "Mouse",
    "Mouse",
    "Mouse",
    "Mouse",
    "Poison Pin",
    "Poison Pin",
    "Drill",
    "Poison Pin",
    "Poison Pin",
    "Drill",
    "Fairy",
    "Fairy",
    "Fox",
    "Fox",
    "Balloon",
    "Balloon",
    "Bat",
    "Bat",
    "Weed",
    "Weed",
    "Flower",
    "Mushroom",
    "Mushroom",
    "Insect",
    "Poison Moth",
    "Mole",
    "Mole",
    "Scratch Cat",
    "Classy Cat",
    "Duck",
    "Duck",
    "Pig",
    "Pig",
    "Puppy",
    "Legendary",
    "Tadpole",
    "Tadpole",
    "Tadpole",
    "Psi",
    "Psi",
    "Psi",
    "Superpower",
    "Superpower",
    "Superpower",
    "Flower",
    "Flycatcher",
    "Flycatcher",
    "Jellyfish",
    "Jellyfish",
    "Rock",
    "Rock",
    "Megaton",
    "Fire Horse or Unique Horn",
    "Fire Horse or Unique Horn",
    "Dopey",
    "Hermit Crab",
    "Magnet",
    "Magnet",
    "Wild Duck",
    "Twin Bird",
    "Triple Bird",
    "Sea Lion",
    "Sea Lion",
    "Sludge",
    "Sludge",
    "Bivalve",
    "Bivalve",
    "Gas",
    "Gas",
    "Shadow",
    "Rock Snake",
    "Hypnosis",
    "Hypnosis",
    "River Crab",
    "Pincer",
    "Ball",
    "Ball",
    "Egg",
    "Coconut",
    "Lonely",
    "Bone Keeper",
    "Kicking",
    "Punching",
    "Licking",
    "Poison Gas",
    "Poison Gas",
    "Spikes",
    "Drill",
    "Egg",
    "Vine",
    "Parent",
    "Dragon",
    "Dragon",
    "Goldfish",
    "Goldfish",
    "Star Shape",
    "Mysterious",
    "Barrier or Dancing",
    "Mantis",
    "Human Shape",
    "Electric",
    "Spitfire",
    "Stag Beetle",
    "Wild Bull",
    "Fish",
    "Atrocious",
    "Transport",
    "Transform",
    "Evolution",
    "Bubble Jet",
    "Lightning",
    "Flame",
    "Virtual",
    "Spiral",
    "Spiral",
    "Shellfish",
    "Shellfish",
    "Fossil",
    "Sleeping",
    "Freeze",
    "Electric",
    "Flame",
    "Dragon",
    "Dragon",
    "Dragon",
    "Genetic",
    "New Species"
};

enum colors
{
    RED,
    ORANGE,
    BLUE,
    YELLOW,
    GREEN,
    BLACK,
    BROWN,
    TAN,
    PURPLE,
    GRAY,
    SILVER,
    WHITE,
    PINK
};

std::vector<colors> bodyColorVec
{
    /*KANTO*/
    GREEN,
    GREEN,
    GREEN,
    ORANGE,
    RED,
    ORANGE,
    BLUE,
    PURPLE,
    BLUE,
    GREEN,
    GREEN,
    PURPLE,
    BROWN,
    YELLOW,
    YELLOW,
    BROWN,
    BROWN,
    BROWN,
    PURPLE,
    BROWN,
    BROWN,
    BROWN,
    PURPLE,
    PURPLE,
    YELLOW,
    YELLOW,
    YELLOW,
    YELLOW,
    PURPLE,
    BLUE,
    BLUE,
    PURPLE,
    PURPLE,
    PURPLE,
    PINK,
    PINK,
    ORANGE,
    ORANGE,
    PINK,
    PINK,
    BLUE,
    BLUE,
    BLUE,
    BLUE,
    BLUE,
    ORANGE,
    ORANGE,
    PURPLE,
    PURPLE,
    BROWN,
    BROWN,
    TAN,
    TAN,
    YELLOW,
    BLUE,
    TAN,
    TAN,
    ORANGE,
    ORANGE,
    BLUE,
    BLUE,
    BLUE,
    TAN,
    TAN,
    TAN,
    GRAY,
    GRAY,
    GRAY,
    YELLOW,
    YELLOW,
    YELLOW,
    BLUE,
    BLUE,
    BROWN,
    BROWN,
    BROWN,
    TAN,
    TAN,
    PINK,
    PINK,
    SILVER,
    SILVER,
    TAN,
    BROWN,
    BROWN,
    WHITE,
    WHITE,
    PURPLE,
    PURPLE,
    PURPLE,
    PURPLE,
    PURPLE,
    PURPLE,
    PURPLE,
    GRAY,
    YELLOW,
    YELLOW,
    ORANGE,
    ORANGE,
    RED,
    WHITE,
    PINK,
    BROWN,
    BROWN,
    BROWN,
    BROWN,
    BROWN,
    PINK,
    PURPLE,
    PURPLE,
    GRAY,
    GRAY,
    PINK,
    BLUE,
    BROWN,
    BLUE,
    BLUE,
    ORANGE,
    ORANGE,
    BROWN,
    PURPLE,
    WHITE,
    GREEN,
    PURPLE,
    YELLOW,
    ORANGE,
    BROWN,
    BROWN,
    ORANGE,
    BLUE,
    BLUE,
    PURPLE,
    BROWN,
    BLUE,
    YELLOW,
    ORANGE,
    PINK,
    BLUE,
    BLUE,
    BROWN,
    BROWN,
    PURPLE,
    TAN,
    BLUE,
    YELLOW,
    YELLOW,
    BLUE,
    BLUE,
    TAN,
    PURPLE,
    PINK
};

struct heightWeightData
{
    unsigned short feet;
    unsigned short inches;
    float weight;
};

std::vector<heightWeightData> heightWeightVec
{
    /*KANTO*/
    {2, 4, 15.2},
    {3, 3, 28.7},
    {6, 7, 220.5},
    {2, 0, 18.7},
    {3, 7, 41.9},
    {5, 7, 199.5},
    {1, 8, 19.8},
    {3, 3, 49.6},
    {5, 3, 188.5},
    {1, 0, 6.4},
    {2, 4, 21.8},
    {3, 7, 70.5},
    {1, 0, 7.1},
    {2, 0, 22.0},
    {3, 3, 65.0},
    {1, 0, 4.0},
    {3, 7, 66.1},
    {4, 11, 87.1},
    {1, 0, 7.7},
    {2, 4, 40.8},
    {1, 0, 4.4},
    {3, 11, 83.8},
    {6, 7, 15.2},
    {11, 6, 143.3},
    {1, 4, 13.2},
    {2, 7, 66.1},
    {2, 0, 26.5},
    {3, 3, 65.0},
    {1, 4, 15.4},
    {2, 7, 44.1},
    {4, 3, 132.3},
    {1, 8, 19.8},
    {2, 11, 43.0},
    {4, 7, 136.7},
    {2, 0, 16.5},
    {4, 3, 88.2},
    {2, 0, 21.8},
    {3, 7, 43.9},
    {1, 8, 12.1},
    {3, 3, 26.5},
    {2, 7, 16.5},
    {5, 3, 121.3},
    {1, 8, 11.9},
    {2, 7, 19.0},
    {3, 11, 41.0},
    {1, 0, 11.9},
    {3, 3, 65.0},
    {3, 3, 66.1},
    {4, 11, 27.6},
    {0, 8, 1.8},
    {2, 4, 73.4},
    {1, 4, 9.3},
    {3, 3, 70.5},
    {2, 7, 43.2},
    {5, 7, 168.9},
    {1, 8, 61.7},
    {3, 3, 70.5},
    {2, 4, 41.9},
    {6, 3, 341.7},
    {2, 0, 27.3},
    {3, 3, 44.1},
    {4, 3, 119.0},
    {2, 11, 43.0},
    {4, 3, 124.6},
    {4, 11, 105.8},
    {2, 7, 43.0},
    {4, 11, 155.4},
    {5, 3, 286.6},
    {2, 4, 8.8},
    {3, 3, 14.1},
    {5, 7, 34.2},
    {2, 11, 100.3},
    {5, 3, 121.3},
    {1, 4, 44.1},
    {3, 3, 231.5},
    {4, 7, 661.4},
    {3, 3, 66.1},
    {5, 7, 209.4},
    {3, 11, 79.4},
    {5, 3, 173.1},
    {1, 0, 13.2},
    {3, 3, 132.3},
    {2, 7, 33.1},
    {4, 7, 86.4},
    {5, 11, 187.8},
    {3, 7, 198.4},
    {5, 7, 264.6},
    {2, 11, 66.1},
    {3, 11, 66.1},
    {1, 0, 8.8},
    {4, 11, 292.1},
    {4, 3, 0.2},
    {5, 3, 0.2},
    {4, 11, 89.3},
    {28, 10, 463.0},
    {3, 3, 71.4},
    {5, 3, 166.7},
    {1, 4, 14.3},
    {4, 3, 132.3},
    {1, 8, 22.9},
    {3, 11, 146.8},
    {1, 4, 5.5},
    {6, 7, 264.6},
    {1, 4, 14.3},
    {3, 3, 99.2},
    {4, 11, 109.8},
    {4, 7, 110.7},
    {3, 11, 144.4},
    {2, 0, 2.2},
    {3, 11, 20.9},
    {3, 3, 253.5},
    {6, 3, 264.6},
    {3, 7, 76.3},
    {3, 3, 77.2},
    {7, 3, 176.4},
    {1, 4, 17.6},
    {3, 11, 55.1},
    {2, 0, 33.1},
    {4, 3, 86.0},
    {2, 7, 76.1},
    {3, 7, 176.4},
    {4, 3, 120.2},
    {4, 11, 123.5},
    {4, 7, 89.5},
    {3, 7, 66.1},
    {4, 3, 98.1},
    {4, 11, 121.3},
    {4, 7, 194.9},
    {2, 11, 22.0},
    {21, 4, 518.1},
    {8, 2, 485.0},
    {1, 0, 8.8},
    {1, 0, 14.3},
    {3, 3, 63.9},
    {2, 7, 54.0},
    {2, 11, 55.1},
    {2, 7, 80.5},
    {1, 4, 16.5},
    {3, 3, 77.2},
    {1, 8, 25.4},
    {4, 3, 89.3},
    {5, 11, 130.1},
    {6, 11, 1014.1},
    {5, 7, 122.1},
    {5, 3, 116.0},
    {6, 7, 132.3},
    {5, 11, 7.3},
    {13, 1, 36.4},
    {7, 3, 463.0},
    {6, 7, 269.0},
    {1, 4, 8.8}
};

struct pokedexEntryFormat
{
    std::string first;
    std::string second;
};

std::vector<pokedexEntryFormat> pokedexEntriesVec
{
    /*KANTO*/
    {"This Pokemon can be seen napping in bright sunlight.", "There is a seed on its back. By soaking up the sun's rays, the seed grows progressively larger"},
    {"There is a bud on this Pokémon's back. To support its weight, this Pokemon's legs and trunk grow thick and strong.", "If it starts spending more time lying in the sunlight, it's a sign that the bud will bloom into a large flower soon."},
    {"There is a large flower on this Pokemon's back.", "The flower is said to take on vivid colors if it gets plenty of nutrition and sunlight. The flower's aroma soothes the emotions of people."},
    {"The flame that burns at the tip of its tail is an indication of its emotions.", "The flame wavers when this Pokemon is enjoying itself. If the Pokémon becomes enraged, the flame burns fiercely."},
    {"This Pokemon mercilessly destroys its foes using its sharp claws.", "If it encounters a strong foe, it turns aggressive. In this excited state, the flame at the tip of its tail flares with a bluish white color."},
    {"This Pokemon flies around the sky in search of powerful opponents.", "It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself."},
    {"This Pokemon shell is not merely used for protection.", "The shell's rounded shape and the grooves on its surface help minimize resistance in water, enabling this Pokémon to swim at high speeds."},
    {"Its tail is large and covered with a rich, thick fur. The tail becomes increasingly deeper in color as this Pokemon ages.", "The scratches on its shell are evidence of this Pokémon's toughness as a battler."},
    {"This Pokemon has water spouts that protrude from its shell. The water spouts are very accurate.", "They can shoot bullets of water with enough accuracy to strike empty cans from a distance of over 160 feet."},
    {"This Pokemon has a voracious appetite. It can devour leaves bigger than its body right before your eyes.", "From its antenna, this Pokémon releases a terrifically strong odor."},
    {"The shell covering this Pokémon's body is as hard as an iron slab. This Pokemon does not move very much.", "It stays still because it is preparing its soft innards for evolution inside the hard shell."},
    {"This Pokemon has a superior ability to search for delicious honey from flowers.", "It can even search out, extract, and carry honey from flowers that are blooming over six miles from its nest."},
    {"This Pokemon has an extremely acute sense of smell.", "It is capable of distinguishing its favorite kinds of leaves from those it dislikes just by sniffing with its big red proboscis (nose)."},
    {"This Pokemon remains virtually immobile as it clings to a tree.", "on the inside, it is extremely busy as it prepares for its coming evolution. This is evident from how hot the shell becomes to the touch."},
    {"This Pokemon is extremely territorial. No one should ever approach its nest—this is for their own safety.", "If angered, they will attack in a furious swarm."},
    {"This Pokemon has an extremely sharp sense of direction.", "It is capable of unerringly returning home to its nest, however far it may be removed from its familiar surroundings."},
    {"This Pokemon claims a large area as its own territory.", "This Pokémon flies around, patrolling its living space. If its territory is violated, it shows no mercy in thoroughly punishing the foe with its sharp claws."},
    {"This Pokémon has a dazzling plumage of beautifully glossy feathers.", "Many Trainers are captivated by the striking beauty of the feathers on its head, compelling them to choose it as their Pokémon."},
    {"This Pokemon is cautious in the extreme. Even while it is asleep, it constantly listens by moving its ears around.", "It is not picky about where it lives—it will make its nest anywhere."},
    {"This Pokemon sturdy fangs grow steadily. To keep them ground down, it gnaws on rocks and logs.", "It may even chew on the walls of houses."},
    {"This Pokemon has a very loud cry that can be heard over half a mile away.", "If its high, keening cry is heard echoing all around, it is a sign that they are warning each other of danger."},
    {"This Pokemon is recognized by its long neck and elongated beak. They are conveniently shaped for catching prey in soil or water.", "It deftly moves its long and skinny beak to pluck prey."},
    {"This Pokemon curls itself up in a spiral while it rests.", "Assuming this position allows it to quickly respond to a threat from any direction with a glare from its upraised head."},
    {"This Pokémon is terrifically strong in order to constrict things with its body. It can even flatten steel oil drums.", "Once this Pokemon wraps its body around its foe, escaping its crunching embrace is impossible."},
    {"Whenever this Pokemon comes across something new, it blasts it with a jolt of electricity.", "If you come across a blackened berry, it's evidence that this Pokémon mistook the intensity of its charge."},
    {"If the electrical sacs become excessively charged, this Pokemon plants its tail in the ground and discharges.", "Scorched patches of ground will be found near this Pokémon's nest."},
    {"This Pokemon body is configured to absorb water without waste, enabling it to survive in an arid desert.", "This Pokémon curls up to protect itself from its enemies."},
    {"This Pokemon's body is covered by tough spikes, which are hardened sections of its hide.", "Once a year, the old spikes fall out, to be replaced with new spikes that grow out from beneath the old ones."},
    {"This Pokemon has barbs that secrete a powerful poison. They are thought to have developed as protection for this small-bodied Pokémon.", "When enraged, it releases a horrible toxin from its horn."},
    {"When this Pokemon are with their friends or family, they keep their barbs tucked away to prevent hurting each other.", "This Pokémon appears to become nervous if separated from the others."},
    {"This Pokemon's body is encased in extremely hard scales. It is adept at sending foes flying with harsh tackles.", "This Pokémon is at its strongest when it is defending its young."},
    {"This Pokemon has developed muscles for moving its ears. Thanks to them, the ears can be freely moved in any direction.", "Even the slightest sound does not escape this Pokémon's notice."},
    {"This Pokemon has a horn that is harder than a diamond.", "If it senses a hostile presence, all the barbs on its back bristle up at once, and it challenges the foe with all its might."},
    {"This Pokemon's thick tail packs enormously destructive power. With one swing, it can topple a metal transmission tower.", "Once this Pokémon goes on a rampage, there is no stopping it."},
    {"On every night of a full moon, groups of this Pokémon come out to play.", "When dawn arrives, these tired Pokemon return to their quiet mountain retreats and go to sleep nestled up against each other."},
    {"This Pokemon moves by skipping lightly as if it were flying using its wings. Its bouncy step lets it even walk on water.", "It is known to take strolls on lakes on quiet, moonlit nights."},
    {"At the time of its birth, this Pokemon has one white tail.", "The tail separates into six if this Pokémon receives plenty of love from its Trainer. The six tails become magnificently curled."},
    {"This Pokemon casts a sinister light from its bright red eyes to gain total control over its foe's mind.", "This Pokémon is said to live for a thousand years."},
    {"This Pokemon vocal cords can freely adjust the wavelength of its voice.", "This Pokémon uses this ability to sing at precisely the right wavelength to make its foes most drowsy."},
    {"This Pokemon has large, saucerlike eyes. The surfaces of its eyes are always covered with a thin layer of tears.", "If any dust gets in this Pokémon's eyes, it is quickly washed away."},
    {"This Pokemon remains quietly unmoving in a dark spot during the bright daylight hours.", "Prolonged exposure to the sun causes this Pokemon's body to become slightly burned."},
    {"loves to drink the blood of living things. It is particularly active in the pitch black of night.", "This Pokémon flits around in the night skies, seeking fresh blood."},
    {"During the daytime, this Pokemon buries itself in soil to absorb nutrients from the ground using its entire body.", "The more fertile the soil, the glossier its leaves become."},
    {"This Pokemon releases a foul fragrance from the pistil of its flower. When faced with danger, the stench worsens.", "If this Pokémon is feeling calm and secure, it does not release its usual stinky aroma."},
    {"This Pokemon's toxic pollen triggers atrocious allergy attacks.", "Because of this Pokemon's appearance, it is advisable never to approach any attractive flowers in a jungle, however pretty they may be."},
    {"This Pokemon has parasitic mushrooms growing on its back called tochukaso.", "These mushrooms grow large by drawing nutrients from this Bug Pokémon host. They are highly valued as a medicine for extending life."},
    {"This Pokemon is known to infest large trees en masse and drain nutrients from the lower trunk and roots.", "When an infested tree dies, they move onto another tree all at once."},
    {"This Pokemon is said to have evolved with a coat of thin, stiff hair that covers its entire body for protection.", "It possesses large eyes that never fail to spot even minuscule prey."},
    {"This Pokemon is nocturnal.", "Its favorite prey are small insects that gather around streetlights, attracted by the light in the darkness."},
    {"This Pokemon is raised in most farms.", "Wherever this Pokémon burrows, the soil is left perfectly tilled for planting crops. This soil is made ideal for growing delicious vegetables."},
    {"This Pokemon is actually comprised of triplets that emerged from one body.", "As a result, each triplet thinks exactly like the other two triplets. They work cooperatively to burrow endlessly."},
    {"This Pokemon withdraws its sharp claws into its paws to slinkily sneak about without making any incriminating footsteps.", "For some reason, this Pokémon loves shiny coins that glitter with light."},
    {"This Pokemon has six bold whiskers that give it a look of toughness.", "It's whiskers sense air movements to determine what is in the Pokémon's surrounding vicinity. It becomes docile if grabbed by the whiskers."},
    {"This Pokemon uses a mysterious power.", "This Pokémon generates brain waves that are supposedly only seen in sleepers. This discovery spurred controversy among scholars."},
    {"The webbed flippers on its forelegs and hind legs and the streamlined body of this Pokemon give it frightening speed.", "This Pokémon is definitely much faster than even the most athletic swimmer."},
    {"When this Pokemon starts shaking and its nasal breathing turns rough, it's a sure sign that it is becoming angry.", "Because this Pokemon goes into a towering rage almost instantly, it is impossible for anyone to flee its wrath."},
    {"When Primeape becomes furious, its blood circulation is boosted.", "This Pokemon's muscles are made even stronger when angry. However, it also becomes much less intelligent at the same time."},
    {"This Pokemon has a superb sense of smell. Once it smells anything, this Pokémon won't forget the scent, no matter what.", "This Pokemon uses its advanced olfactory sense to determine the emotions of other living things."},
    {"This Pokemon is known for its high speed. It is said to be capable of running over 6,200 miles in a single day and night", "The fire that blazes wildly within this Pokémon's body is its source of power."},
    {"This Pokemon has a very thin skin. It is possible to see the Pokémon's spiral innards right through the skin.", "Despite its thinness, this Pokemon's skin is also very flexible. Even sharp fangs bounce right off it."},
    {"The surface of This Pokemon's body is always wet and slick with a slimy fluid.", "Because of this Pokemon's slippery covering, it can easily slip and slide out of the clutches of any enemy in battle."},
    {"This Pokemon's highly developed, brawny muscles never grow fatigued, however much it exercises.", "This Pokemon is so tirelessly strong, it can swim back and forth across the ocean without effort."},
    {"This Pokemon sleeps for eighteen hours a day. However, it can sense the presence of foes even while it is sleeping.", "This Pokémon can immediately teleport itself to safety."},
    {"emits a peculiar alpha wave if it develops a headache.", "Only those people with a particularly strong psyche can hope to become a Trainer of this Pokémon."},
    {"This Pokemon's brain continually grows, making its head far too heavy to support with its neck.", "This Pokémon holds its head up using its psychokinetic power."},
    {"This Pokemon's muscles are special—they never get sore no matter how much they are used in exercise.", "This Pokémon has sufficient power to hurl a hundred adult humans."},
    {"This Pokemon's thoroughly toned muscles possess the hardness of steel.", "This Pokémon has so much strength, it can easily hold aloft a sumo wrestler on just one finger."},
    {"This Pokemon has the power to hurl anything aside. However, trying to do any work requiring care and dexterity causes its arms to get tangled.", "This Pokémon tends to leap into action before it thinks."},
    {"This Pokemon thin and flexible body lets it bend and sway to avoid any attack, however strong it may be.", "From its mouth, this Pokémon spits a corrosive fluid that melts even iron."},
    {"This Pokemon has a large hook on its rear end. At night, the Pokémon hooks on to a tree branch and goes to sleep.", "If this Pokemon moves around in its sleep, it may wake up to find itself on the ground."},
    {"This Pokemon has a long vine that extends from its head. This vine is waved and flicked about as if it were an animal to attract prey.", "When an unsuspecting prey draws near, this Pokémon swallows it whole."},
    {"This Pokemon's body is largely composed of water. If it is removed from the sea, it dries up like parchment.", "If this Pokémon happens to become dehydrated, put it back into the sea."},
    {"This Pokemon has large red orbs on its head. The orbs glow before lashing the vicinity with a harsh ultrasonic blast.", "This Pokémon's outburst creates rough waves around it."},
    {"The longer a this Pokemon lives, the more its edges are chipped and worn away, making it more rounded in appearance.", "This Pokémon's heart will remain hard, craggy, and rough always."},
    {"This Pokemon grows by feeding on rocks. Apparently, it prefers to eat rocks that are covered in moss.", "This Pokémon eats its way through a ton of rocks on a daily basis."},
    {"This Pokemon lives up on mountaintops.", "If there is a large earthquake, these Pokémon will come rolling down off the mountains en masse to the foothills below."},
    {"This Pokemon is very weak at birth. It can barely stand up.", "This Pokémon becomes stronger by stumbling and falling to keep up with its parent."},
    {"This Pokemon usually can be seen casually cantering in the fields and plains.", "When this Pokémon turns serious, its fiery manes flare and blaze as it gallops its way up to 150 mph."},
    {"This Pokemon uses its tail to catch prey by dipping it in water at the side of a river.", "This Pokémon often forgets what it's doing and often spends entire days just loafing at water's edge."},
    {"This Pokemon's tail has a Shellder firmly attached with a bite.", "This Pokemon grudgingly swims about to catch its prey."},
    {"This Pokemon attaches itself to power lines to feed on electricity.", "If your house has a power outage, check your circuit breakers. You may find a large number of this Pokémon clinging to the breaker box."},
    {"This Pokemon emits a powerful magnetic force that is fatal to mechanical devices.", "Large cities sound sirens to warn citizens of large-scale outbreaks of this Pokémon."},
    {"This Pokemon is always seen with a stalk from a plant of some sort. Apparently, there are good stalks and bad stalks.", "This Pokémon has been known to fight with others over stalks."},
    {"This Pokemon's two heads never sleep at the same time.", "This Pokemon's two heads contain completely identical brains. A scientific study reported that on rare occasions, there will be examples of this Pokémon possessing different sets of brains."},
    {"Watch out if this Pokemon's three heads are looking in three separate directions. It's a sure sign that it is on its guard.", "Don't go near this Pokémon if it's being wary—it may decide to peck you."},
    {"This Pokemon hunts for prey in the frigid sea underneath sheets of ice.", "When it needs to breathe, it punches a hole through the ice with the sharply protruding section of its head."},
    {"This Pokemon loves to snooze on bitterly cold ice.", "The sight of this Pokémon sleeping on a glacier was mistakenly thought to be a mermaid by a mariner long ago."},
    {"This Pokemon's sludgy and rubbery body can be forced through any opening, however small it may be.", "This Pokémon enters sewer pipes to drink filthy wastewater."},
    {"From this Pokemon's body seeps a foul fluid that gives off a nose-bendingly horrible stench.", "Just one drop of this Pokémon's body fluid can turn a pool stagnant and rancid."},
    {"At night, this Pokémon uses its broad tongue to burrow a hole in the seafloor sand and then sleep in it.", "While it is sleeping, this Pokemon closes its shell, but leaves its tongue hanging out."},
    {"This Pokemon is capable of swimming in the sea. It does so by swallowing water, then jetting it out toward the rear.", "This Pokémon can shoots spikes from its shell."},
    {"This Pokemon is largely composed of gaseous matter. When exposed to a strong wind, the gaseous body quickly dwindles away.", "Groups of this Pokémon cluster under the eaves of houses to escape the ravages of wind."},
    {"This is a dangerous Pokémon. If one beckons you while floating in darkness, you must never approach it.", "This Pokémon will try to lick you with its tongue and steal your life away."},
    {"Sometimes, on a dark night, your shadow thrown by a streetlight will suddenly and startlingly overtake you, because of this Pokemon", "This Pokemon can be found running past you, pretending to be your shadow."},
    {"This Pokemon has a magnet in its brain. It acts as a compass so that this Pokémon does not lose direction while it is tunneling.", "As this Pokemon grows older, its body becomes increasingly rounder and smoother."},
    {"If your nose becomes itchy while you are sleeping, it's a sure sign that one of these Pokémon is standing above your pillow and trying to eat your dream through your nostrils.", "This Pokemon finds really fun dreams tasty. When it makes friends with people, it may show them the most delicious dreams it's ever eaten."},
    {"This Pokemon holds a pendulum in its hand. The arcing movement and glitter of the pendulum lull the foe into a deep state of hypnosis.", "While this Pokémon searches for prey, it polishes the pendulum."},
    {"This Pokemon live on beaches, burrowed inside holes dug into the sand.", "On sandy beaches with little in the way of food, these Pokémon can be seen squabbling with each other over territory."},
    {"This Pokemon has an enormous, oversized claw.", "This Pokemon waves its huge claw in the air to communicate with others. However, because the claw is so heavy, the Pokémon quickly tires."},
    {"This Pokemon was first sighted at a company that manufactures Poké Balls.", "The fact that this Pokémon looks very similar to a Poké Ball remains a mystery."},
    {"This Pokemon eats electricity in the atmosphere.", "On days when lightning strikes, you can see this Pokémon exploding all over the place from eating too much electricity."},
    {"This Pokémon consists of six eggs that form a closely knit cluster. The six eggs attract each other and spin around", "When cracks increasingly appear on the eggs, Exeggcute is close to evolution."},
    {"This Pokemon originally came from the tropics. Its heads steadily grow larger from exposure to strong sunlight.", "It is said that when the heads fall off, they group together to form a different Pokemon."},
    {"This Pokemon pines for the mother it will never see again. Seeing a likeness of its mother in the full moon, it cries.", "The stains on the skull the Pokémon wears are made by the tears it sheds."},
    {"This Pokemon is the evolved form of a Pokemon that has overcome its sadness at the loss of its mother and grown tough.", "This Pokémon's tempered and hardened spirit is not easily broken."},
    {"This Pokemon legs freely contract and stretch. Using these springlike legs, it bowls over foes with devastating kicks.", "After battle, this Pokemon rubs down its legs and loosens the muscles to overcome fatigue."},
    {"This Pokemon is said to possess the spirit of a boxer who had been working toward a world championship.", "This Pokémon has an indomitable spirit and will never give up in the face of adversity."},
    {"Whenever this Pokemon comes across something new, it will unfailingly give it a lick. It does so because it memorizes things by texture and by taste.", "It is somewhat put off by sour things."},
    {"If this Pokemon becomes agitated, it raises the toxicity of its internal gases and jets them out from all over its body.", "This Pokémon may also overinflate its round body, then explode."},
    {"This Pokemon loves the gases given off by rotted kitchen garbage.", "This Pokémon will find a dirty, unkempt house and make it its home. At night, when the people in the house are asleep, it will go through the trash."},
    {"This Pokemon runs in a straight line, smashing everything in its path.", "This Pokemon is not bothered even if it rushes headlong into a block of steel. It may feel some pain from the collision the next day, however."},
    {"This Pokemon's horn can crush even uncut diamonds. One sweeping blow of its tail can topple a building.", "This Pokémon's hide is extremely tough. Even direct cannon hits don't leave a scratch."},
    {"This Pokemon lays nutritionally excellent eggs on an everyday basis.", "This Pokemon's eggs are so delicious, they are easily and eagerly devoured by even those people who have lost their appetite."},
    {"This Pokemon's vines snap off easily if they are grabbed. This happens without pain, allowing it to make a quick getaway.", "This Pokemon's lost vines are replaced by newly grown vines the very next day."},
    {"If you come across one of these Pokemon in their youth, playing by itself, you must never disturb it or attempt to catch it.", "The baby Pokémon's parent is sure to be in the area, and it will become violently enraged at you."},
    {"This Pokemon eats small insects and moss off of rocks.", "If the ocean current turns fast, this Pokémon anchors itself by wrapping its tail around rocks or coral to prevent being washed away."},
    {"This Pokemon sleeps after wriggling itself between the branches of coral.", "Those trying to harvest coral are occasionally stung by this Pokémon's poison barbs if they fail to notice it."},
    {"This Pokemon is a very beautiful Pokémon with fins that billow elegantly in water.", "Don't let your guard down around this Pokémon, it could ram you powerfully with its horn."},
    {"In the autumn, the males can be seen performing courtship dances in riverbeds to woo females.", "During the season of courtship, this Pokémon's body coloration is at its most beautiful."},
    {"This Pokemon's center section has an organ called the core that shines bright red.", "If you go to a beach toward the end of summer, the glowing cores of these Pokémon look like the stars in the sky."},
    {"This Pokemon's center section glows brightly in seven colors.", "Because of its luminous nature, this Pokémon has been given the nickname “the gem of the sea."},
    {"This Pokemon is a master of pantomime.", "This Pokemon's gestures and motions convince watchers that something unseeable actually exists. Once the watchers are convinced, the unseeable thing exists as if it were real."},
    {"This Pokemon is blindingly fast. Its blazing speed enhances the effectiveness of the twin scythes on its forearms.", "This Pokémon's scythes are so effective, they can slice through thick logs in one wicked stroke."},
    {"This Pokemon walks rhythmically, swaying and shaking its hips as if it were dancing.", "This Pokemon's motions are so bouncingly alluring, people seeing it are compelled to shake their hips without giving any thought to what they are doing."},
    {"When a storm arrives, gangs of this Pokémon compete with each other to scale heights that are likely to be stricken by lightning bolts.", "Some towns use this Pokemon in place of lightning rods."},
    {"In battle, this Pokemon blows out intensely hot flames from all over its body to intimidate its opponent.", "This Pokémon's fiery bursts create heat waves that ignite grass and trees in its surroundings."},
    {"This Pokemon is astoundingly strong. It can grip a foe weighing twice its weight in its horns and easily lift it.", "This Pokémon's movements turn sluggish in cold places."},
    {"This Pokémon is not satisfied unless it is rampaging at all times.", "If there is no opponent for this Pokemon to battle, it will charge at thick trees and knock them down to calm itself."},
    {"This is a pathetic excuse for a Pokémon that is only capable of flopping and splashing.", "This flopping and splashing behavior prompted scientists to undertake research into it."},
    {"Upon evolution, this Pokemon's brain cells undergo a structural transformation.", "It is said that this transformation is to blame for this Pokémon's wildly violent nature."},
    {"People have driven this Pokemon almost to the point of extinction.", "In the evenings, this Pokémon is said to sing plaintively as it seeks what few others of its kind still remain."},
    {"This Pokemon rearranges its cell structure to transform itself into other shapes.", "If this Pokemon tries to transform itself into something by relying on its memory, this Pokémon manages to get details wrong."},
    {"This Pokemon has an unstable genetic makeup that suddenly mutates due to the environment in which it lives.", "Radiation from various stones causes this Pokémon to evolve."},
    {"This Pokemon underwent a spontaneous mutation and grew fins and gills that allow it to live underwater.", "This Pokémon has the ability to freely control water."},
    {"This Pokemon's cells generate a low level of electricity.", "This pokemon's power is amplified by the static electricity of its fur, enabling the Pokémon to drop thunderbolts. The bristling fur is made of electrically charged needles."},
    {"This Pokemon's fluffy fur has a functional purpose, it releases heat into the air so that its body does not get excessively hot.", "This Pokémon's body temperature can rise to a maximum of 1,650 degrees Fahrenheit."},
    {"This Pokemon is capable of reverting itself entirely back to program data and entering cyberspace.", "This Pokémon is copy protected so it cannot be duplicated by copying."},
    {"This Pokemon is one of the ancient and long-since-extinct Pokémon that have been regenerated from fossils by people.", "If attacked by an enemy, it withdraws itself inside its hard shell."},
    {"This Pokemon uses its tentacles to capture its prey.", "It is believed to have become extinct because its shell grew too large and heavy, causing its movements to become too slow and ponderous."},
    {"This Pokemon has been regenerated from a fossil. However, in extremely rare cases, living examples have been discovered.", "The Pokémon has not changed at all for 300 million years."},
    {"This Pokemon swam underwater to hunt for its prey in ancient times.", "The Pokémon was apparently evolving from being a water dweller to living on land as evident from the beginnings of change in its gills and legs."},
    {"This Pokemon is from the age of dinosaurs. It was regenerated from genetic material extracted from amber.", "It is imagined to have been the king of the skies in ancient times."},
    {"This Pokemon's typical day consists of nothing more than eating and sleeping.", "It is such a docile Pokémon that there are children who use its expansive belly as a place to play."},
    {"This Pokemon has the ability to control ice.", "The flapping of this Pokemon's wings chills the air. As a result, it is said that when this Pokémon flies, snow will fall."},
    {"This Pokemon has the ability to control electricity.", "This Pokemon usually lives in thunderclouds. It gains power if it is stricken by lightning bolts."},
    {"This Pokemon has the ability to control fire", "If this Pokémon is injured, it is said to dip its body in the molten magma of a volcano to burn and heal itself."},
    {"This Pokemon continually molts and sloughs off its old skin.", "It does so because the life energy within its body steadily builds to reach uncontrollable levels."},
    {"This Pokemon stores an enormous amount of energy inside its body.", "It is said to alter weather conditions in its vicinity by discharging energy from the crystals on its neck and tail."},
    {"This Pokemon is capable of circling the globe in just 16 hours.", "It is a kindhearted Pokémon that leads lost and foundering ships in a storm to the safety of land."},
    {"This Pokemon is a Pokémon that was created by genetic manipulation.", "Even though the scientific power of humans created this Pokémon's body, they failed to endow it with a compassionate heart."},
    {"This Pokemon is said to possess the genetic composition of all Pokémon.", "It is capable of making itself invisible at will, so it entirely avoids notice even if it approaches people."}
};